/* Stable driving controls and an intact first-person body. */
(()=>{
 const hud=cockpit205.hud;
 const outside=document.createElement('button');outside.id='outsideView221';outside.textContent='Outside view';outside.onclick=()=>{roadsterControls203.setView(roadsterControls203.viewIndex===0?2:0);window.tutorial219?.record('outside');};hud.insertBefore(outside,hud.querySelector('.cockpit205-main'));
 const css=document.createElement('style');css.textContent='#cockpit205{display:flex;flex-direction:column;gap:6px;width:170px!important}#cockpit205[hidden]{display:none!important}#cockpit205 #ignition211,#cockpit205 #exitCar220,#cockpit205 #outsideView221{height:44px!important;min-height:44px!important;flex:0 0 44px;margin:0!important;font:600 12px/1.15 system-ui!important;white-space:nowrap}#cockpit205 #outsideView221{border:1px solid #d1ba8355;border-radius:12px;background:#203d34e8;color:#f1dfb8}#cockpit205 .cockpit205-quick{height:44px;flex:0 0 44px;margin:0!important}#cockpit205 .cockpit205-main{height:66px;flex:0 0 66px}#lesson219{max-width:calc(100vw - 24px)}';document.head.appendChild(css);
 const enter=enterCar77;enterCar77=function(){const was=car77?.riding,result=enter();if(!was&&car77?.riding){roadsterControls203.setView(2);keys={};joy.x=joy.z=0;rat.userData.motionX=rat.userData.motionZ=0;}return result;};
 // Remove the driver's seat from the cockpit foreground; restore after rendering.
 const render=renderer.render;renderer.render=function(sceneArg,cam){const hidden=[];if(sceneArg===scene&&cam===camera&&car77?.riding&&roadsterControls203.viewIndex>0&&roadsterControls203.viewIndex!==4){car77.visual.traverse(o=>{if(o.isMesh&&/seat cushion|seat back|Seat stitching/i.test(o.name)&&(o.position.x<0||(o.name==='Seat stitching'&&(o.geometry.computeBoundingBox(),o.geometry.boundingBox.max.x<0)))){hidden.push([o,o.visible]);o.visible=false;}});}try{return render.call(this,sceneArg,cam);}finally{for(const [o,v]of hidden)o.visible=v;}};
 const tick=tickWorld38;tickWorld38=function(dt){tick(dt);outside.textContent=roadsterControls203.viewIndex===0?'Hands cockpit':'Outside view';};
})();
