/* Three short car-control pages keep the phone HUD clear. */
(()=>{
 const api=motoring206,drawer=cockpit205.drawer,grid=drawer.querySelector('.cockpit205-grid'),existing=Array.from(grid.children),[left,right,brake,wipers,radio,map,smoke,exit]=existing;
 const tabs=document.createElement('nav');tabs.className='cockpit206-tabs';tabs.setAttribute('aria-label','Car control pages');drawer.insertBefore(tabs,grid);const groups={Drive:[left,right,brake],Cabin:[radio,wipers,smoke],City:[map]};let selected='Drive';
 function add(group,label,fn){const b=document.createElement('button');b.className='cockpit205-secondary';b.textContent=label;b.onclick=fn;b.onpointerdown=e=>e.stopPropagation();groups[group].push(b);return b;}
 const ignition=add('Drive','Start engine',api.ignition),lights=add('Drive','Headlights: off',api.lights);add('Cabin','Glovebox',()=>{cockpit205.toggle(false);api.glovebox();});
 for(const [name,dir]of [['Look left','left'],['Look right','right'],['Look behind','back']]){const b=add('Cabin',name,()=>{});b.setAttribute('aria-label',name+' · hold');b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();b.setPointerCapture?.(e.pointerId);api.beginLook(dir);b.setAttribute('aria-pressed','true');};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>{api.endLook();b.setAttribute('aria-pressed','false');});}

 const tabButtons={};function select(name){selected=name;for(const [group,buttons]of Object.entries(groups)){for(const b of buttons)b.hidden=group!==name;tabButtons[group].setAttribute('aria-pressed',String(group===name));}}
 for(const name of Object.keys(groups)){const b=document.createElement('button');b.textContent=name;b.onclick=()=>select(name);b.className='cockpit206-tab';b.onpointerdown=e=>e.stopPropagation();tabs.appendChild(b);tabButtons[name]=b;for(const control of groups[name])grid.appendChild(control);}exit.classList.add('cockpit206-exit');drawer.appendChild(exit);select('Drive');
 const delivery=document.createElement('button');delivery.className='cockpit206-delivery';delivery.setAttribute('aria-label','Open active delivery');delivery.onclick=api.jobs;cockpit205.hud.insertBefore(delivery,cockpit205.hud.querySelector('.cockpit205-quick'));delivery.hidden=true;
 const foot=document.getElementById('pipActions205');if(foot)foot.onclick=api.actions;
 const tickBefore=tickWorld38;let refresh=0;tickWorld38=function(dt){tickBefore(dt);refresh+=dt;if(refresh<.12)return;refresh=0;const c=car77;if(c){ignition.textContent=c.ignition206?'Stop engine':'Start engine';ignition.setAttribute('aria-pressed',String(!!c.ignition206));lights.textContent=c.lights206?'Headlights: on':'Headlights: off';lights.setAttribute('aria-pressed',String(!!c.lights206));const note=cockpit205.hud.querySelector('.cockpit205-note');note.textContent=c.ignition206?'HOLD TO SLIDE':'ENGINE OFF';}const p=api.target();delivery.hidden=!p;if(p&&c){const distance=Math.round(Math.hypot(c.g.position.x-p.x,c.g.position.z-p.z));delivery.textContent=(api.data().job.stage==='pickup'?'Pickup':'Deliver')+' · '+p.name+' · '+distance+'m';}};
 const style=document.createElement('style');style.textContent='#cockpit205 .cockpit206-tabs{display:flex;gap:5px;margin-bottom:10px}#cockpit205 .cockpit206-tab{width:33%;min-height:38px;background:#ffffff08;color:#ecdfc3;border:1px solid #ffffff16;border-radius:9px;font:600 11px system-ui}#cockpit205 .cockpit206-tab[aria-pressed=true]{background:#d5b16f;color:#20352e}#cockpit205 .cockpit206-exit{margin-top:10px!important;width:100%!important}#cockpit205 .cockpit206-delivery{width:100%;padding:8px;margin-bottom:8px!important;font:600 10px/1.3 system-ui;background:#223e35eb;color:#edca87;border:1px solid #ccb48255;border-radius:10px}.glove206>div{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:10px 0;border-bottom:1px solid #3453}.glove206 strong,.glove206 span{grid-column:1/-1}.glove206 button{min-height:44px;border:0;border-radius:9px;background:#28473d;color:#fff1ce}.glove206 button:disabled{opacity:.35}';document.head.appendChild(style);
 window.cockpit206={select,groups};
})();
