/* Roadster integration: actual Pip skeleton contacts, centre controls and cockpit camera. */
(function(scope){
function solveArm203(THREE,rig,side,target,pole){
 const bones=rig.userData.pipBones,arm=bones[side+'Arm'],fore=bones[side+'ForeArm'],hand=bones[side+'Hand'];if(!arm||!fore||!hand)return;
 if(pole){
  rig.updateWorldMatrix(true,true);const V=()=>new THREE.Vector3(),a=arm.getWorldPosition(V()),e=fore.getWorldPosition(V()),w=hand.getWorldPosition(V()),l1=a.distanceTo(e),l2=e.distanceTo(w),direction=target.clone().sub(a),d=Math.max(.0001,Math.min(direction.length(),l1+l2-.00001));direction.normalize();const bend=pole.clone().sub(a);bend.addScaledVector(direction,-bend.dot(direction));if(bend.lengthSq()<1e-8)bend.set(0,-1,0);bend.normalize();const along=(l1*l1-l2*l2+d*d)/(2*d),height=Math.sqrt(Math.max(0,l1*l1-along*along)),elbow=a.clone().addScaledVector(direction,along).addScaledVector(bend,height);
  const orient=(joint,end,goal)=>{rig.updateWorldMatrix(true,true);const origin=joint.getWorldPosition(V()),from=end.getWorldPosition(V()).sub(origin).normalize(),to=goal.clone().sub(origin).normalize(),delta=new THREE.Quaternion().setFromUnitVectors(from,to),world=joint.getWorldQuaternion(new THREE.Quaternion());joint.quaternion.copy(joint.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(delta.multiply(world))).normalize();joint.updateWorldMatrix(false,true);};orient(arm,fore,elbow);orient(fore,hand,a.clone().addScaledVector(direction,d));return hand.getWorldPosition(V()).distanceTo(target);
 }
 for(let i=0;i<18;i++){for(const bone of [fore,arm]){rig.updateWorldMatrix(true,true);const origin=bone.getWorldPosition(new THREE.Vector3()),from=hand.getWorldPosition(new THREE.Vector3()).sub(origin),to=target.clone().sub(origin);if(from.lengthSq()<1e-10||to.lengthSq()<1e-10)continue;const delta=new THREE.Quaternion().setFromUnitVectors(from.normalize(),to.normalize()),world=bone.getWorldQuaternion(new THREE.Quaternion());bone.quaternion.copy(bone.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(delta.multiply(world))).normalize();bone.updateWorldMatrix(false,true);}if(hand.getWorldPosition(new THREE.Vector3()).distanceTo(target)<.001)break;}
 return hand.getWorldPosition(new THREE.Vector3()).distanceTo(target);
}
scope.solveArm203=solveArm203;
if(typeof module!=='undefined'){module.exports={solveArm203};return;}
let firstPerson=false,savedCamera=null,headHidden=null,viewIndex=0;
const viewNames=["Outside", "Driver", "Hands", "Dashboard", "Shoulder"];
let armMeshes=[];
// Reversible deformation of the supplied textured paw mesh; this rig has no finger bones.
// Curl beyond the palm around the rim, rather than rotating a flat open hand.
function clearGrip220(g){if(!g)return;g.traverse(m=>{const d=m.userData.grip220;if(d){m.geometry=d.base;d.curled.dispose();delete m.userData.grip220;}});}
function grip220(g){g.traverse(m=>{if(!m.isSkinnedMesh||m.userData.grip220)return;const base=m.geometry,si=base.attributes.skinIndex,sw=base.attributes.skinWeight;if(!si||!sw)return;const ids=['Left','Right'].map(side=>m.skeleton.bones.indexOf(g.userData.pipBones[side+'Hand'])).filter(i=>i>=0);if(!ids.length)return;const geo=base.clone(),p=geo.attributes.position;for(const id of ids){const to=m.skeleton.boneInverses[id].clone().multiply(m.bindMatrix),back=to.clone().invert();for(let i=0;i<p.count;i++){let weight=0;for(let k=0;k<4;k++)if(si.array[i*4+k]===id)weight+=sw.array[i*4+k];if(weight<.01)continue;const original=new THREE.Vector3().fromBufferAttribute(base.attributes.position,i),v=original.clone().applyMatrix4(to);const blend=THREE.MathUtils.smoothstep(v.y,0,5)*Math.min(1,weight*1.5);v.x*=.72;v.y*=.72;v.z*=.8;if(v.y>4.5){const distance=v.y-4.5,radius=4.2,theta=Math.min(2.35,distance/radius);v.y=4.5+Math.sin(theta)*radius;v.z-=(1-Math.cos(theta))*radius;}v.applyMatrix4(back);original.lerp(v,blend);p.setXYZ(i,original.x,original.y,original.z);}}p.needsUpdate=true;geo.computeVertexNormals();m.userData.grip220={base,curled:geo};m.geometry=geo;});}
function handsOnly(g){g.traverse(m=>{if(!m.isSkinnedMesh)return;const source=m.geometry,geo=source.clone(),skin=source.attributes.skinIndex,weights=source.attributes.skinWeight,indices=source.index,keep=[];if(!skin||!weights)return;const armIds=new Set();m.skeleton.bones.forEach((b,i)=>{for(let a=b;a;a=a.parent)if(/^(Left|Right)(Arm|ForeArm|Hand)$/.test(a.name)){armIds.add(i);break;}});const included=i=>{let w=0;for(let j=0;j<4;j++)if(armIds.has(skin.array[i*4+j]))w+=weights.array[i*4+j];return w>.5;};for(let i=0;i<(indices?indices.count:source.attributes.position.count);i+=3){const tri=[0,1,2].map(j=>indices?indices.getX(i+j):i+j);if(tri.every(included))keep.push(...tri);}geo.setIndex(keep);geo.clearGroups();armMeshes.push([m,source]);m.geometry=geo;});}
function clearHands(){for(const [m,g]of armMeshes){m.geometry.dispose();m.geometry=g;}armMeshes=[];}
function restoreHead(){if(headHidden){headHidden.bone.scale.copy(headHidden.scale);headHidden=null;}}
function leaveCamera(){clearGrip220(rat);clearHands();restoreHead();firstPerson=false;viewIndex=0;if(savedCamera){camera.near=savedCamera.near;camera.fov=savedCamera.fov;camera.updateProjectionMatrix();savedCamera=null;}gameCam.ready=false;document.body.classList.remove('driving203');viewButton.textContent='Driver view';}
addCar77=function(){disposeCar77();if(phase!=='scavenge'||!root)return;const g=createRoadster202(THREE);g.position.set(5.4,0,17.6);g.rotation.y=-12*Math.PI/180;root.add(g);car77={g,visual:g.children[0],owner:root,riding:false,speed:0,steer:0,horn:0,audio:null,...g.userData,handbrake:false,brakeAngle:0,gear:0,reach:null,gearCooldown:0};registerSolid62(g);};
const enter=enterCar77;enterCar77=function(){const done=enter();if(car77?.riding){rat.scale.copy(car77.originalScale);car77.handbrake=false;car77.reach=null;car77.travelYaw=car77.g.rotation.y;car77.drifting=false;document.body.classList.add('driving203');sayToast('Drive: joystick / WASD · B handbrake · V driver view · H horn');}return done;};
const grabBefore203=grab;grab=function(){if(car77?.riding)return exitCar77();return grabBefore203();};
const exit=exitCar77;exitCar77=function(){const result=exit();if(!car77?.riding)leaveCamera();return result;};
const dispose=disposeCar77;disposeCar77=function(){leaveCamera();dispose();};
function reach(kind){if(car77?.riding)car77.reach={kind,time:0,duration:kind==='brake'?.95:.8};}
function handbrake(){if(!car77?.riding||!gameplayActive())return;car77.handbrake=!car77.handbrake;reach('brake');brakeButton.textContent=car77.handbrake?'Release brake':'Handbrake';brakeButton.setAttribute('aria-pressed',String(car77.handbrake));}
const horn=honk77;honk77=function(){const before=car77?.horn;horn();if(car77?.horn>0&&!before)reach('horn');};
function view(next,force=false){if(!car77?.riding||(!force&&!gameplayActive()))return;clearGrip220(rat);viewIndex=Number.isInteger(next)?Math.max(0,Math.min(4,next)):(viewIndex+1)%viewNames.length;clearHands();if(!viewIndex){leaveCamera();document.body.classList.add('driving203');return;}if(!savedCamera)savedCamera={near:camera.near,fov:camera.fov,yaw:gameCam.yaw,pitch:gameCam.pitch};firstPerson=true;camera.near=.012;camera.fov=camera.aspect<.7?90:76;camera.updateProjectionMatrix();if(viewIndex===2)handsOnly(rat);viewButton.textContent=viewNames[viewIndex]+' · V';}
const brakeButton=document.createElement('button'),viewButton=document.createElement('button');for(const [b,label,fn]of [[brakeButton,'Handbrake',handbrake],[viewButton,'Driver view',view]]){b.className='btn';b.textContent=label;b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();fn();};carPanel77.appendChild(b);}carPanel77.id='carPanel203';carPanel77.children[1].onpointerdown=e=>{e.preventDefault();e.stopPropagation();exitCar77();};
const style=document.createElement('style');style.textContent='#carPanel203{flex-wrap:wrap;max-width:230px;justify-content:flex-end;gap:6px!important}#carPanel203 button{padding:10px 12px;font-size:13px}.driving203 #navigation201,.driving203 #cameraTools,.driving203 #geckoWhistle193{display:none!important}.driving203 #padJ,.driving203 #padB,.driving203 #padR,.driving203 #tail67{display:none!important}';document.head.appendChild(style);
addEventListener('keydown',e=>{if(e.repeat||!car77?.riding||!gameplayActive())return;if(e.key.toLowerCase()==='v'){e.preventDefault();view();}if(e.key.toLowerCase()==='b'){e.preventDefault();handbrake();}});
// Use the smaller car's footprint and keep parked-car collision out of its own movement.
blockedCar77=function(p,radius=.39){return wallSolids().some(o=>o.h>.12&&Math.abs(p.x-o.x)<o.hx+radius&&Math.abs(p.z-o.z)<o.hz+radius)||p.x<-19.4||p.x>29.4||p.z<.4||p.z>36.6;};
controlCar77=function(dt,options={}){const c=car77;if(!c?.riding)return null;if(c.owner!==root||phase!=='scavenge'){disposeCar77();return null;}dt=Math.min(.033,Math.max(0,dt));if(!gameplayActive()||document.hidden||options.locked){c.speed=0;stopEngine77();return 0;}
 const throttle=THREE.MathUtils.clamp((keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0)-joy.z,-1,1),steer=THREE.MathUtils.clamp((keys.a||keys.arrowleft?1:0)-(keys.d||keys.arrowright?1:0)-joy.x,-1,1);const motion=vehiclePhysics219.step(c,{throttle,steer,engine:c.ignition206!==false,blocked:!!window.vehicle219?.interlocked()},dt,window.vehicle219?.tuning());c.horn=Math.max(0,c.horn-dt);
 const yaw=c.g.rotation.y+motion.yawRate*dt,from=c.g.position.clone();c.travelYaw=c.travelYaw===undefined?yaw:c.travelYaw+Math.atan2(Math.sin(yaw-c.travelYaw),Math.cos(yaw-c.travelYaw))*(1-Math.exp(-(c.drifting?1.7:12)*dt));const to=from.clone().add(new THREE.Vector3(Math.sin(c.travelYaw),0,Math.cos(c.travelYaw)).multiplyScalar(c.speed*dt));let blocked=false;for(const x of [-.38,.38])for(const z of [-.60,0,.60]){const offset=new THREE.Vector3(x,0,z).applyAxisAngle(new THREE.Vector3(0,1,0),yaw),a=from.clone().add(offset),p=to.clone().add(offset);if(blockedCar77(p,.12)){blocked=true;break;}const goal=p.clone();resolveGeometry62(p,a);if(p.distanceTo(goal)>.01)blocked=true;}if(!blocked){c.g.position.copy(to);c.g.rotation.y=yaw;}else c.speed=0;
 rat.position.copy(c.seat).applyAxisAngle(new THREE.Vector3(0,1,0),c.g.rotation.y).add(c.g.position);rat.rotation.y=c.g.rotation.y;Object.assign(rat.userData,{air:false,vy:0,vel:0});c.wheel.rotation.z=-c.steer*.55;for(const h of c.hubs)h.rotation.x-=c.speed*dt/c.wheelRadius;for(const p of c.steeringPivots)if(p.position.z>0)p.rotation.y=c.steeringAngle219||0;
 c.gearCooldown=Math.max(0,c.gearCooldown-dt);const gear=c.speed<-.3?-1:c.speed>5.83?3:c.speed>2.78?2:c.speed>.15?1:0;if(gear!==c.gear&&!c.reach&&!c.gearCooldown){if(gear)reach('gear');c.gear=gear;c.gearCooldown=1;}if(c.reach){c.reach.time+=dt;if(c.reach.time>=c.reach.duration)c.reach=null;}c.brakeAngle=THREE.MathUtils.damp(c.brakeAngle,c.handbrake?-.45:0,7,dt);c.brake.rotation.x=c.brakeAngle;
 if(voiceOn){engine77();if(c.audio){const a=c.audio;a.osc.frequency.setTargetAtTime(48+Math.abs(c.speed)*14,a.osc.context.currentTime,.1);}}else stopEngine77();return 0;};
function pose(g){const c=car77,u=g.userData;if(!c?.riding||!u.drive77||!u.pipBones?.Hips)return;const b=u.pipBones;grip220(g);for(const side of ['Left','Right'])for(const [part,angle]of [['UpLeg',-1.15],['Leg',1.05]]){const name=side+part;if(b[name]&&u.pipRest[name]){b[name].quaternion.copy(u.pipRest[name]);b[name].rotateX(angle);}}restoreHead();g.updateWorldMatrix(true,true);c.g.updateWorldMatrix(true,true);
 const r=c.reach,q=r?r.time/r.duration:0,weight=r?Math.min(1,q/.28,(1-q)/.28):0;
 // Plant the pelvis on the cushion, independently of the character's animation root.
 const hip=c.g.localToWorld(c.seat.clone().add(new THREE.Vector3(weight*.015,.040-weight*.012,.047))),actual=b.Hips.getWorldPosition(new THREE.Vector3());g.position.add(hip.sub(actual));g.updateWorldMatrix(true,true);
 if(r?.kind==='mirror'&&r.target){const shoulder=b[(r.side||'Left')+'Arm'];if(shoulder){const shift=r.target.getWorldPosition(new THREE.Vector3()).sub(shoulder.getWorldPosition(new THREE.Vector3()));shift.multiplyScalar(Math.max(0,1-.085/shift.length())*Math.max(0,weight));g.position.add(shift);g.updateWorldMatrix(true,true);}}
 const errors={};for(const side of ['Left','Right']){const arm=b[side+'Arm'];if(!arm)continue;for(const name of [side+'Arm',side+'ForeArm',side+'Hand'])if(b[name]&&u.pipRest[name])b[name].quaternion.copy(u.pipRest[name]);g.updateWorldMatrix(true,true);const shoulder=c.wheel.worldToLocal(arm.getWorldPosition(new THREE.Vector3())),sign=shoulder.x<0?-1:1;let target=c.wheel.localToWorld(new THREE.Vector3(sign*.105,.004,-.035));
 // Lean across the bench for distant mirrors; the other paw braces by the torso.
 if(r?.kind==='mirror'&&side!==(r.side||'Left'))target=arm.getWorldPosition(new THREE.Vector3()).add(new THREE.Vector3(0,-.08,.02));
 // The hand nearest the centre console reaches, the other keeps steering.
 if(r&&side===(r.side||'Left')){const destination=r.target?r.target.getWorldPosition(new THREE.Vector3()):r.kind==='brake'?c.brakeTarget.getWorldPosition(new THREE.Vector3()):r.kind==='ignition'?c.ignitionTarget.getWorldPosition(new THREE.Vector3()):r.kind==='radio'?c.radioTarget.getWorldPosition(new THREE.Vector3()):r.kind==='gear'?c.gearTarget.getWorldPosition(new THREE.Vector3()):c.wheel.localToWorld(new THREE.Vector3(0,0,-.015));target.lerp(destination,Math.max(0,weight));}
 const pole=arm.getWorldPosition(new THREE.Vector3()).add(new THREE.Vector3(sign*.035,-.16,-.07).applyAxisAngle(new THREE.Vector3(0,1,0),c.g.rotation.y));errors[side]=solveArm203(THREE,g,side,target,pole);
 // Orient the wrist in the wheel frame: the model's hand has no finger joints.
 // Fingers point over the rim; curled tips turn inward, with the thumbs above the grip.
 const hand=b[side+'Hand'];if(hand){const wheelQ=c.wheel.getWorldQuaternion(new THREE.Quaternion()),basis=new THREE.Matrix4().makeBasis(new THREE.Vector3(0,sign,0),new THREE.Vector3(0,0,1),new THREE.Vector3(sign,0,0)),grip=new THREE.Quaternion().setFromRotationMatrix(basis);const world=wheelQ.multiply(grip);const local=hand.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(world);hand.quaternion.slerp(local,1-(r&&side===(r.side||'Left')?Math.max(0,weight):0));g.updateWorldMatrix(true,true);}
 }
 c.handErrors203=errors;if(scope.pipSmoke205)scope.pipSmoke205.pose(g);if(firstPerson&&viewIndex!==4&&b.Head){headHidden={bone:b.Head,scale:b.Head.scale.clone()};b.Head.scale.setScalar(.0001);g.updateWorldMatrix(true,true);}
}
const make=makeRat;makeRat=function(){const g=make(),animate=g.animate;g.animate=function(...args){restoreHead();animate(...args);pose(g);};return g;};
const cam=tickGameplayCamera;tickGameplayCamera=function(dt){if(!car77?.riding||!firstPerson||photo.active){cam(dt);return;}const c=car77;const fov=camera.aspect<.7?90:76;if(camera.fov!==fov){camera.fov=fov;camera.updateProjectionMatrix();}const lookYaw=THREE.MathUtils.clamp(gameCam.yaw-savedCamera.yaw,-1.45,1.45),lookDown=THREE.MathUtils.clamp(gameCam.pitch-savedCamera.pitch,-.55,1.48);c.g.updateWorldMatrix(true,true);const eye=c.g.localToWorld(new THREE.Vector3(c.seat.x,viewIndex===3?.57:viewIndex===4?.65:.555,viewIndex===3?-.22:viewIndex===4?-.63:-.40)),direction=new THREE.Vector3(Math.sin(lookYaw)*Math.cos(lookDown),-Math.sin(lookDown),Math.cos(lookYaw)*Math.cos(lookDown)).applyAxisAngle(new THREE.Vector3(0,1,0),c.g.rotation.y);camera.position.copy(eye);camera.lookAt(eye.clone().add(direction));$('cameraTools').style.display='none';};
scope.roadsterControls203={handbrake,view,setView:n=>view(n,true),withFullBody(fn){const swapped=armMeshes.map(([m,g])=>{const partial=m.geometry;m.geometry=g;return [m,partial];}),hidden=headHidden;if(hidden){hidden.bone.scale.copy(hidden.scale);rat.updateWorldMatrix(true,true);}try{return fn();}finally{for(const [m,g]of swapped)m.geometry=g;if(hidden){hidden.bone.scale.setScalar(.0001);rat.updateWorldMatrix(true,true);}}},pose,get viewIndex(){return viewIndex;}};
})(typeof window!=='undefined'?window:globalThis);
