/* Shared corrections used by the live-model review. */
(()=>{
 const T=THREE,V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
 const mat=(color,roughness=.8)=>new T.MeshStandardMaterial({color,roughness});
 const mesh=(g,geo,m,x=0,y=0,z=0,name='')=>{const o=new T.Mesh(geo,m);o.position.set(x,y,z);o.name=name;o.userData.noInk=true;o.receiveShadow=true;g.add(o);return o;};
 // One continuous plaster face, with a real circular aperture, replaces the tiled board treatment.
 const make=makeHouse;makeHouse=function(s){const g=make(s);const keepsakes=g.getObjectByName('Pip’s keepsakes');if(keepsakes)g.remove(keepsakes);const shell=new T.Group();shell.name='Continuous lime plaster';g.add(shell);const plaster=mat(0xe5dfcf),wood=mat(0x745638),shadow=mat(0x514b3d);
  const shape=new T.Shape();shape.moveTo(-HW/2,0);shape.lineTo(HW/2,0);shape.lineTo(HW/2,3.3);shape.lineTo(-HW/2,3.3);shape.closePath();const hole=new T.Path();hole.absarc(2,1.9,1.12,0,Math.PI*2,true);shape.holes.push(hole);mesh(shell,new T.ShapeGeometry(shape,64),plaster,0,0,-HD/2+.13,'Unbroken back plaster');
  function side(side,lo,hi){const p=mesh(shell,new T.PlaneGeometry(hi-lo,3.3),plaster,side*(HW/2-.09),1.65,(lo+hi)/2,'Unbroken side plaster');p.rotation.y=side<0?Math.PI/2:-Math.PI/2;}
  side(1,-HD/2,HD/2);side(-1,-HD/2,DOORZ-.7);side(-1,DOORZ+.7,HD/2);const lintel=mesh(shell,new T.PlaneGeometry(1.4,.6),plaster,-HW/2+.09,3,DOORZ);lintel.rotation.y=Math.PI/2;
  for(const b of g.userData.boards230||[]){if(!b.wall)continue;const refresh=b.refresh;b.refresh=function(){refresh();b.group.visible=false;const paint=homestead230.state().paint[b.id];if(paint)plaster.color.setHex(({sage:0x809377,cream:0xd6c7a6,blue:0x6d8c96,clay:0xac7861})[paint]||0xe5dfcf);};b.refresh();}
  // Two localized failures retain the flood-damaged character without covering the room in seams.
  for(const [id,x,y]of [['back-0-1',-6.7,.65],['back-3-2',6.1,1.7]]){const sh=new T.Shape();sh.moveTo(-.35,0);sh.lineTo(.25,-.07);sh.lineTo(.51,.28);sh.lineTo(.34,.5);sh.lineTo(.43,.76);sh.lineTo(-.16,.66);sh.lineTo(-.39,.35);sh.closePath();const patch=mesh(shell,new T.ShapeGeometry(sh),shadow,x,y,-HD/2+.145,'Localized plaster damage');const group=new T.Group();shell.add(group);for(let j=0;j<4;j++)mesh(group,new T.BoxGeometry(.5,.035,.03),wood,x+.02,y+.09+j*.16,-HD/2+.165,'Exposed lath');const b=g.userData.boards230.find(b=>b.id===id);if(b){const refresh=b.refresh;b.refresh=function(){refresh();patch.visible=group.visible=!homestead230.state().boards[id];};b.refresh();}}
  // Retain a single useful shelf; remove loose trim strips and the former tiled skin.
  return g;
 };
 const audioStats={open:0,close:0,wiper:0,window:0,roof:0,switch:0};let ac=null;
 // Rounded envelopes and filtered friction: never start a full-volume noise impulse.
 function sound(kind){if(!voiceOn||document.hidden)return;ac=ac||sfxCtx();if(!ac)return;ac.resume().catch(()=>{});audioStats[kind]=(audioStats[kind]||0)+1;
  const now=ac.currentTime;
  function friction(delay,duration,level,hz,band=false){const source=ac.createBufferSource(),buffer=ac.createBuffer(1,Math.ceil(duration*ac.sampleRate),ac.sampleRate),data=buffer.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){brown=(brown+.035*(Math.random()*2-1))/1.035;data[i]=brown*5;}source.buffer=buffer;const filter=ac.createBiquadFilter();filter.type=band?'bandpass':'lowpass';filter.frequency.value=hz;filter.Q.value=.55;const gain=ac.createGain(),t=now+delay;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(level,t+duration*.18);gain.gain.setTargetAtTime(0,t+duration*.35,duration*.14);gain.gain.linearRampToValueAtTime(0,t+duration);source.connect(filter).connect(gain).connect(ac.destination);source.start(t);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
  function tone(delay,duration,hz,level,end=hz){const o=ac.createOscillator(),g=ac.createGain(),t=now+delay;o.type='sine';o.frequency.setValueAtTime(hz,t);o.frequency.linearRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(level,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(ac.destination);o.start(t);o.stop(t+duration);o.onended=()=>{o.disconnect();g.disconnect();};}
  if(kind==='close'){friction(0,.23,.17,420);tone(.02,.25,92,.15,67);friction(.065,.12,.055,1200);}
  else if(kind==='open'){friction(0,.16,.12,1400,true);friction(.09,.42,.095,650);tone(.06,.18,185,.03,140);}
  else if(kind==='wiper'){friction(0,.46,.09,780,true);tone(.025,.31,210,.010,180);}
  else if(kind==='roof'||kind==='window'){const d=kind==='roof'?1.3:.85;friction(0,d,.085,650);tone(0,d,kind==='roof'?125:175,.034,kind==='roof'?110:155);}
  else friction(0,.07,.055,950);
 }
 for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>{if(voiceOn){ac=ac||sfxCtx();ac?.resume().catch(()=>{});}},{capture:true});
 function setup(c){const a=c.cabin219;if(!a||c.corrected242)return;c.corrected242=true;
  // Old decorative oval mirrors occupied the same space as the working mirror faces.
  c.visual.traverse(o=>{if(o.name==='Wing mirror'){o.visible=false;o.raycast=()=>{};}});
  for(const d of a.doors){d.glass.geometry.dispose();const s=new T.Shape();s.moveTo(-.67,0);s.lineTo(0,0);s.lineTo(-.025,.445);s.quadraticCurveTo(-.30,.47,-.65,.43);s.closePath();d.glass.geometry=new T.ShapeGeometry(s,16);d.glass.material=new T.MeshStandardMaterial({color:0xd5e2dd,transparent:true,opacity:.10,roughness:.12,metalness:0,side:T.DoubleSide,depthWrite:false});d.glass.rotation.y=-Math.PI/2;d.glass.position.z=0;d.glass.position.x=d.pivot.position.x<0?.09:-.09;d.glass.renderOrder=3;}
  c.audio242={doors:a.doors.map(d=>d.value),windows:vehicle219.data().windows,roof:vehicle219.data().roof,wiperBucket:Math.floor((c.wiperPhase||0)/Math.PI),lights:c.lights206};
 }
 const controls=document.createElement('button');controls.id='carControls242';controls.className='btn';controls.textContent='Car controls';controls.style.cssText='position:fixed;left:12px;top:44%;z-index:35;font:600 12px system-ui;padding:11px 13px;display:none';document.body.appendChild(controls);
 const panel=document.createElement('section');panel.id='carPanel242';panel.hidden=true;panel.innerHTML='<header><b>Roadster controls</b><button id="closeCar242" aria-label="Close car controls">×</button></header><div id="carActions242"></div><label>Mirror <select id="mirrorSelect242"><option value="0">Centre</option><option value="1">Left</option><option value="2">Right</option></select></label><label>Left / right<input id="mirrorYaw242" aria-label="Mirror horizontal angle" type="range" min="-.6" max=".6" step=".01"></label><label>Up / down<input id="mirrorPitch242" aria-label="Mirror vertical angle" type="range" min="-.4" max=".4" step=".01"></label><p id="carStatus242">Park to adjust the cabin.</p>';document.body.appendChild(panel);
 const css=document.createElement('style');css.textContent='#carPanel242{position:fixed;z-index:60;left:50%;top:50%;transform:translate(-50%,-50%);width:min(340px,91vw);max-height:76vh;overflow:auto;padding:17px;border:1px solid #a2a58b;background:#203b33f5;border-radius:16px;color:#eee5cd;font:13px system-ui;box-shadow:0 12px 50px #0006}#carPanel242[hidden]{display:none}#carPanel242 header{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}#carPanel242 button,#carPanel242 select{font:600 12px system-ui;border:1px solid #839381;background:#354d3e;color:#fff0d2;border-radius:8px;min-height:40px;padding:8px}#carActions242{display:grid;grid-template-columns:1fr 1fr;gap:7px}#carPanel242 label{display:flex;align-items:center;gap:9px;margin-top:12px}#carPanel242 input{min-width:0;flex:1}#carStatus242{font-size:11px;opacity:.8;margin-top:12px}';document.head.appendChild(css);
 const buttons={};for(const [id,label,fn]of [['hood','Open hood',()=>vehicle219.toggle('hood')],['roof','Close roof',()=>vehicle219.toggle('roof')],['windows','Raise windows',()=>vehicle219.toggle('windows')],['door0','Open left door',()=>vehicle219.toggle('door',0)],['door1','Open right door',()=>vehicle219.toggle('door',1)],['wipers','Wipers: Auto',()=>{car77.wiperMode=((car77.wiperMode||0)+1)%3;sound('switch');}],['lights','Lights',()=>{car77.lights206=!car77.lights206;}],['sound','Sound: on',()=>{voiceOn=!voiceOn;sound('switch');}]]){const b=document.createElement('button');b.id=id+'242';b.textContent=label;b.onclick=()=>{if(Math.abs(car77.speed)>.08)return;fn();refresh();};panel.querySelector('#carActions242').appendChild(b);buttons[id]=b;}
 function near(){return phase==='scavenge'&&car77?.owner===root&&(car77.riding||rat.position.distanceTo(car77.g.position)<2.4);}
 function refresh(){if(!car77?.cabin219)return;const a=car77.cabin219,s=vehicle219.data();buttons.hood.textContent=a.hoodOpen?'Close hood':'Open hood';buttons.roof.textContent=s.roof?'Open roof':'Close roof';buttons.windows.textContent=s.windows?'Lower windows':'Raise windows';a.doors.forEach((d,i)=>buttons['door'+i].textContent=(d.open?'Close ':'Open ')+(i?'right':'left')+' door');buttons.wipers.textContent='Wipers: '+['Auto','On','Off'][car77.wiperMode||0];buttons.lights.textContent=car77.lights206?'Lights off':'Lights on';buttons.sound.textContent=voiceOn?'Sound: on':'Sound: off';const moving=Math.abs(car77.speed)>.08;Object.values(buttons).forEach(b=>b.disabled=moving);$('carStatus242').textContent=moving?'Stop the car to use these controls.':'Roof, doors and mirrors work from either view.';}
 controls.onclick=()=>{panel.hidden=!panel.hidden;keys={};joy.x=joy.z=0;refresh();mirrorSliders();};$('closeCar242').onclick=()=>panel.hidden=true;
 function mirrorSliders(){const s=vehicle219.data().mirrors[Number($('mirrorSelect242').value)];$('mirrorYaw242').value=s.yaw;$('mirrorPitch242').value=s.pitch;}
 $('mirrorSelect242').onchange=mirrorSliders;for(const id of ['mirrorYaw242','mirrorPitch242'])$(id).oninput=()=>{if(!near()||Math.abs(car77.speed)>.08)return;const index=Number($('mirrorSelect242').value),m=car77.cabin219.mirrors[index],s=vehicle219.data().mirrors[index];s.yaw=Number($('mirrorYaw242').value);s.pitch=Number($('mirrorPitch242').value);m.yaw219=s.yaw;m.pitch219=s.pitch;save();};
 const control=controlCar77;controlCar77=function(dt,options){return control(dt,panel.hidden?options:{...options,locked:true});};
 const tick=tickWorld38;tickWorld38=function(dt){tick(dt);controls.style.display=near()&&gameplayActive()&&!photo.active?'block':'none';if(!near()||!gameplayActive())panel.hidden=true;const c=car77;if(!c||c.owner!==root||!c.cabin219)return;setup(c);const a=c.cabin219,q=c.audio242,s=vehicle219.data();
  // Glass keeps its shape while retracting into the door: no scaling or floating rectangle.
  for(const d of a.doors){d.glass.scale.y=1;d.glass.position.y=.215-(1-a.windowValue)*.37;d.glass.visible=a.windowValue>.015;}
  if(!gameplayActive()||document.hidden)return;a.doors.forEach((d,i)=>{if(q.doors[i]<=.001&&d.value>.001)sound('open');if(q.doors[i]>.001&&d.value<=.001)sound('close');q.doors[i]=d.value;});for(const kind of ['windows','roof'])if(q[kind]!==s[kind]){sound(kind==='windows'?'window':'roof');q[kind]=s[kind];}if(q.lights!==c.lights206){sound('switch');q.lights=c.lights206;}const bucket=Math.floor((c.wiperPhase||0)/Math.PI);if(bucket!==q.wiperBucket){sound('wiper');q.wiperBucket=bucket;}if(!panel.hidden)refresh();
 };
 window.fixes242={setup,sound,audioStats,panel,refresh};
})();
