/* A small persistent motoring loop, cockpit equipment and grounded leisure poses. */
(()=>{
 const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),Y=V(0,1,0),clamp=THREE.MathUtils.clamp;
 const shops=[{id:'cafe',name:'Crumb Café',x:-.5,z:49},{id:'vinyl',name:'Vinyl & Tail',x:6,z:57},{id:'market',name:'Night Market',x:12.5,z:49}];
 const bays=[{id:'willow',name:'Willow lay-by',x:-12,z:53},{id:'lantern',name:'Lantern corner',x:24,z:58},{id:'rooftops',name:'Rooftop overlook',x:18,z:64}];
 let world=null,rest=null,look=null,mirrorClock=0,mirrorIndex=0,rendering=false;
 function data(){const d=home.car206||(home.car206={});d.stash||={};d.parking||={};d.deliveries||=0;return d;}
 function count(obj){return Object.values(obj).reduce((a,n)=>a+Math.max(0,Number(n)||0),0);}
 function transfer(id,into,n=5){if(!ITEMS[id])return 0;const d=data(),from=into?inv:d.stash,to=into?d.stash:inv,capacity=into?20-count(d.stash):bagCapacity()-totalBag(),amount=Math.max(0,Math.min(Math.floor(n),Math.floor(from[id]||0),capacity));if(!amount)return 0;from[id]-=amount;to[id]=(to[id]||0)+amount;save();bag();return amount;}
 function nearCar(){return phase==='scavenge'&&car77?.owner===root&&(car77.riding||rat.position.distanceTo(car77.g.position)<2.2);}
 function glovebox(){if(!nearCar())return sayToast('Stand beside the roadster to use its glovebox.');if(car77.riding&&Math.abs(car77.speed)>.2)return sayToast('Stop before opening the glovebox.');const d=data(),ids=Object.keys(ITEMS).filter(id=>inv[id]>0||d.stash[id]>0);modal('Glovebox · '+count(d.stash)+' / 20',`<p>Your supplies stay in the car between visits. Each tap moves up to five.</p><div class="glove206">${ids.map((id,i)=>`<div><strong>${craftEscape40(ITEMS[id].name)}</strong><span>Bag ${inv[id]||0} · Car ${d.stash[id]||0}</span><button data-store206="${i}" ${!inv[id]||count(d.stash)>=20?'disabled':''}>Store</button><button data-take206="${i}" ${!d.stash[id]||totalBag()>=bagCapacity()?'disabled':''}>Take</button></div>`).join('')||'<p>Your bag and glovebox are empty.</p>'}</div>`,[['Close',closeModal]]);for(const [selector,into]of [['data-store206',true],['data-take206',false]])$('modalBody').querySelectorAll('['+selector+']').forEach(b=>b.onclick=()=>{transfer(ids[Number(b.getAttribute(selector))],into);glovebox();});}
 function target(){const job=data().job;return job?shops[job.stage==='pickup'?job.from:job.to]:null;}
 function accept(){const d=data();if(d.job)return;const from=d.deliveries%3;d.job={from,to:(from+1)%3,stage:'pickup'};save();jobs();}
 function deliver(){const d=data(),p=target();if(!p||!car77?.riding||Math.abs(car77.speed)>.2||Math.hypot(car77.g.position.x-p.x,car77.g.position.z-p.z)>1.8)return false;if(d.job.stage==='pickup'){d.job.stage='deliver';sayToast('Parcel loaded. Deliver to '+target().name+'.');}else{d.deliveries++;d.job=null;home.pantry||={};home.pantry.foil=(home.pantry.foil||0)+3;home.pantry.nail=(home.pantry.nail||0)+2;sayToast('Delivery complete: 3 foil and 2 nails stored at home.');}save();return true;}
 function jobs(){const d=data(),p=target(),near=p&&car77?.riding&&Math.abs(car77.speed)<.2&&Math.hypot(car77.g.position.x-p.x,car77.g.position.z-p.z)<1.8;modal('City deliveries',d.job?`<p><b>${d.job.stage==='pickup'?'Pick up at':'Deliver to'} ${p.name}</b></p><p>Follow the gold parcel marker. Stop in the marked loading bay, then collect or deliver here.</p><p>Reward: 3 foil + 2 nails, sent to home storage.</p>`:`<p>Carry small parcels between the café, record shop and market.</p><p>${d.deliveries} deliveries completed. No timer.</p><p>Reward: 3 foil + 2 nails per delivery, sent to home storage.</p>`,d.job?[[d.job.stage==='pickup'?'Pick up parcel':'Deliver parcel',()=>{if(deliver())jobs();},!near],['Show destination',()=>openYard201('delivery206')],['Cancel delivery',()=>{d.job=null;save();jobs();}],['Close',closeModal]]:[['Accept delivery',accept],['City map',()=>openYard201('city')],['Close',closeModal]]);}
 function parking(){const d=data();modal('Hidden parking · '+Object.keys(d.parking).length+' / 3','<p>Explore the edges of the city. Stop fully inside a painted bay for two seconds to discover it.</p><p>Each discovery sends 2 foil to home storage.</p>'+bays.map(b=>'<p>'+(d.parking[b.id]?'✓ '+b.name:'◇ Undiscovered bay')+'</p>').join(''),[['Map',()=>openYard201('city')],['Close',closeModal]]);}
 function destinations(){const d=data(),p=target();return [...(p?[{...p,id:'delivery206',icon:'◆',name:(d.job.stage==='pickup'?'Pickup: ':'Delivery: ')+p.name,detail:'Stop in the marked loading bay, then open City deliveries.'}]:[]),...bays.filter(b=>d.parking[b.id]).map(b=>({...b,id:'parking-'+b.id,icon:'P',detail:'Discovered parking spot. Stop here for a quiet break.'}))];}
 function part(parent,w,h,d,pos,color,name){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.6}));m.position.copy(pos);m.name=name;m.userData.noInk=true;parent.add(m);return m;}
 function attachCar(){const c=car77;if(!c||c.equipment206)return;c.equipment206=true;c.ignition206=false;c.lights206=false;c.mirrors206=[];c.headlights206=[];c.gauges206=[];
 const key=new THREE.Object3D();key.position.set(-.11,.36,-.12);c.g.add(key);c.ignitionTarget=key;const ignition=part(c.g,.012,.008,.03,key.position,0xcac3a5,'Ignition key');c.key206=ignition;
 for(const x of [-.315,.315]){const light=new THREE.SpotLight(0xffe3af,0,15,.42,.6,1.3);light.position.set(x,.34,.77);const target=new THREE.Object3D();target.position.set(x,.02,8);c.g.add(light,target);light.target=target;c.headlights206.push(light);}
 c.g.traverse(m=>{if(m.isMesh&&m.name==='Round headlight')m.userData.originalEmissive206=m.material.emissiveIntensity;});
 for(const [x,y,z,r,max]of [[-.30,.56,.070,.035,5.5],[-.18,.56,.070,.024,1]]){const pivot=new THREE.Group();pivot.position.set(x,y,z);c.visual.add(pivot);const needle=part(pivot,.004,r,.003,V(0,r*.35,0),0xd5a84f,'Moving gauge needle');pivot.userData.max=max;c.gauges206.push(pivot);}
 for(const [x,y,z,w,h,res]of [[0,.635,.09,.13,.053,192],[-.49,.512,.137,.069,.041,128],[.49,.512,.137,.069,.041,128]]){const rt=new THREE.WebGLRenderTarget(res,Math.round(res*.5),{minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter});rt.texture.wrapS=THREE.RepeatWrapping;rt.texture.repeat.x=-1;rt.texture.offset.x=1;const face=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:rt.texture,side:THREE.DoubleSide}));face.position.set(x,y,z);face.rotation.y=Math.PI;face.name='Working rear-view mirror';face.userData.noInk=true;c.g.add(face);part(c.g,w+.009,h+.009,.007,V(x,y,z+.004),0x35443d,'Mirror frame');const cam=new THREE.PerspectiveCamera(60,2,.03,90);c.mirrors206.push({face,rt,cam,x,y,z});}
 }
 function ignition(){const c=car77;if(!c?.riding||!gameplayActive())return;if(Math.abs(c.speed)>.2)return sayToast('Stop before switching the engine off.');c.ignition206=!c.ignition206;c.reach={kind:'ignition',time:0,duration:.7};c.key206.rotation.z=c.ignition206?.5:0;if(!c.ignition206)stopEngine77();else {engine77();cockpit205.toggle(false);}sayToast(c.ignition206?'Engine running.':'Engine off.');}
 function lights(){if(!car77?.riding||!gameplayActive())return;car77.lights206=!car77.lights206;}
 const engineBefore=engine77;engine77=function(){if(car77?.ignition206===false)return;return engineBefore();};
 const add=addCar77;addCar77=function(){add();attachCar();seed();};
 const enter=enterCar77;enterCar77=function(){stand();const r=enter();if(car77?.riding){attachCar();car77.ignition206=false;stopEngine77();window.cockpit206?.select('Drive');cockpit205.toggle(true);sayToast('Turn the ignition on in Car controls.');}return r;};
 const exit=exitCar77;exitCar77=function(){endLook();const r=exit();if(car77&&!car77.riding)car77.ignition206=false;return r;};
 const controlCar=controlCar77;controlCar77=function(dt,options){const c=car77;if(c?.riding&&!c.ignition206){const brake=c.handbrake;c.handbrake=true;const r=controlCar(dt,options);c.handbrake=brake;return r;}return controlCar(dt,options);};
 function beginLook(direction){if(!car77?.riding||!gameplayActive())return;if(look)return;look={direction,view:roadsterControls203.viewIndex};if(!look.view)roadsterControls203.setView(1);}
 function endLook(){if(!look)return;const view=look.view;look=null;if(car77?.riding)roadsterControls203.setView(view);}
 const cameraBefore=tickGameplayCamera;tickGameplayCamera=function(dt){cameraBefore(dt);if(!look||!car77?.riding||photo.active)return;const c=car77,x=look.direction==='left'?-1:look.direction==='right'?1:0,z=look.direction==='back'?-1:-.3;camera.position.copy(c.g.localToWorld(V(c.seat.x,.535,-.31)));camera.lookAt(c.g.localToWorld(V(c.seat.x+x,.47,-.31+z)));};
 for(const event of ['pointerup','pointercancel','blur'])addEventListener(event,endLook);
 const renderBefore=renderer.render;renderer.render=function(s,cam){const c=car77;if(!rendering&&s===scene&&cam===camera&&c?.riding&&c.mirrors206&&roadsterControls203.viewIndex>0&&!photo.active&&mirrorClock>.18){mirrorClock=0;const m=c.mirrors206[mirrorIndex++%c.mirrors206.length],target=renderer.getRenderTarget(),visibility=c.g.visible;rendering=true;try{m.cam.position.copy(c.g.localToWorld(V(m.x,m.y,m.z)));m.cam.lookAt(c.g.localToWorld(V(m.x*4,.35,-10)));c.g.visible=false;renderer.setRenderTarget(m.rt);roadsterControls203.withFullBody(()=>renderBefore.call(renderer,s,m.cam));}finally{c.g.visible=visibility;renderer.setRenderTarget(target);rendering=false;}}return renderBefore.call(renderer,s,cam);};
 function seed(){if(phase!=='scavenge'||world?.owner===root)return;world={owner:root,benches:[],parkTime:0,parkId:null};for(const [x,z,yaw]of [[8,20,0],[-12,60,Math.PI/2],[24,46,-Math.PI/2]]){const g=new THREE.Group();g.name='Pip resting bench';g.position.set(x,0,z);g.rotation.y=yaw;root.add(g);part(g,1.1,.055,.35,V(0,.24,0),0x80694c,'Bench seat');part(g,1.1,.22,.045,V(0,.36,-.17),0x80694c,'Bench back');for(const side of [-1,1])part(g,.06,.23,.3,V(side*.42,.115,0),0x34463d,'Bench legs');registerSolid62(g);world.benches.push(g);}
 for(const b of bays){for(const dx of [-.65,.65])part(root,.04,.012,1.9,V(b.x+dx,.008,b.z),0xc3bda0,'Quiet parking bay');part(root,1.34,.012,.04,V(b.x,.008,b.z-.95),0xc3bda0,'Parking end line');}
 const ring=new THREE.Mesh(new THREE.RingGeometry(.65,.72,32),new THREE.MeshBasicMaterial({color:0xe8be66,side:THREE.DoubleSide,transparent:true,opacity:.75,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.visible=false;root.add(ring);world.marker=ring;const marker=markerText('PARCEL');marker.scale.setScalar(.2);root.add(marker);world.label=marker;marker.visible=false;
 }
 function canRest(){const u=rat?.userData;return phase==='scavenge'&&u&&!car77?.riding&&!u.air&&!u.swim66&&!u.geckoRide88&&!u.bird71&&!u.rope66&&!u.wallState&&!u.job67?.lock;}
 function nearestBench(){return world?.owner===root?world.benches.find(g=>rat.position.distanceTo(g.position)<1.6):null;}
 function relax(kind){if(rest){stand();return;}if(!canRest())return;if(kind==='lean'&&!nearCar())return sayToast('Stand beside the parked roadster.');const bench=kind==='sit'?nearestBench():null;if(kind==='sit'&&!bench)return sayToast('Find a bench by the yard road or city edges.');rest={kind,bench,owner:root,from:rat.position.clone(),yaw:rat.rotation.y,time:0};pipSmoke205.dispose();sayToast(kind==='sit'?'Pip sits down. Move to stand up.':'Pip leans on the roadster. Move to stand up.');}
 function stand(){if(!rest)return;rat.position.copy(rest.from);rat.rotation.y=rest.yaw;rest=null;rat.userData.air=false;rat.userData.vy=0;}
 function restPose(g){if(!rest||g!==rat||rest.owner!==root)return;const b=g.userData.pipBones,u=g.userData;if(!b?.Hips)return;const seat=rest.kind==='sit',base=seat?rest.bench:car77?.g;if(!base){stand();return;}const anchor=base.localToWorld(seat?V(0,.285,.025):V(-.51,.24,-.30));g.rotation.y=base.rotation.y+(seat?0:-Math.PI/2);const blend=THREE.MathUtils.smoothstep(rest.time,0,.65);for(const side of ['Left','Right'])for(const [part,a]of [['UpLeg',seat?-1.1:side==='Left'?-.13:0],['Leg',seat?1.15:side==='Left'?.22:0]]){const name=side+part;if(b[name]&&u.pipRest[name]){b[name].quaternion.copy(u.pipRest[name]);b[name].rotateX(a*blend);}}if(b.Spine&&u.pipRest.Spine){b.Spine.quaternion.copy(u.pipRest.Spine);b.Spine.rotateX((seat?.06:-.35)*blend);}g.updateWorldMatrix(true,true);g.position.add(anchor.sub(b.Hips.getWorldPosition(V())).multiplyScalar(blend));g.updateWorldMatrix(true,true);for(const side of ['Left','Right']){const target=seat?b.Hips.getWorldPosition(V()).add(V(side==='Left'?.05:-.05,.07,.065).applyAxisAngle(Y,g.rotation.y)):base.localToWorld(V(-.47,.385,-.30+(side==='Left'?.06:-.06)));for(const part of ['Arm','ForeArm','Hand']){const name=side+part;if(b[name]&&u.pipRest[name])b[name].quaternion.copy(u.pipRest[name]);}(rest.errors||(rest.errors={}))[side]=solveArm203(THREE,g,side,target);} }
 const controlBefore=control;control=function(dt,options){if(rest){const u=rat.userData,moving=Math.abs(joy.x)+Math.abs(joy.z)>.1||['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].some(k=>keys[k]);if(!canRest()||rest.owner!==root||moving)stand();else {if(gameplayActive())rest.time+=Math.min(dt,.05);return 0;}}return controlBefore(dt,options);};
 function actions(){modal('Pip’s actions','<p>Take a quiet break beside the roadster or on a bench.</p>',[[pipSmoke205.state?'Put out cigarette':'Light cigarette',()=>{closeModal();pipSmoke205.toggle();}],[rest?'Stand up':'Lean on car',()=>{closeModal();rest?stand():relax('lean');},!rest&&!nearCar()],['Sit on bench',()=>{closeModal();relax('sit');},!nearestBench()],['Glovebox',glovebox,!nearCar()],['City deliveries',jobs],['Close',closeModal]]);}
 const tickBefore=tickWorld38;tickWorld38=function(dt){tickBefore(dt);if(phase!=='scavenge'){if(rest)stand();return;}seed();attachCar();if(!gameplayActive()||document.hidden){endLook();return;}mirrorClock+=Math.min(.05,dt);const c=car77;if(c){for(const l of c.headlights206)l.intensity=c.lights206?1.8:0;if(!c.lamps209){c.lamps209=[];c.g.traverse(m=>{if(m.name==='Round headlight')c.lamps209.push(m);});}for(const m of c.lamps209)m.material.emissiveIntensity=c.lights206?1.8:.25;for(let i=0;i<c.gauges206.length;i++){const value=i===0?Math.abs(c.speed)/5.5:c.ignition206?.16+Math.abs(c.speed)/7:0;c.gauges206[i].rotation.z=THREE.MathUtils.damp(c.gauges206[i].rotation.z,2.3-clamp(value,0,1)*4.6,8,dt);}if(c.riding&&Math.abs(c.speed)<.12&&Math.abs(Math.cos(c.g.rotation.y))>.92){const b=bays.find(b=>Math.abs(c.g.position.x-b.x)<.35&&Math.abs(c.g.position.z-b.z)<.6);if(b&&!data().parking[b.id]){world.parkTime=world.parkId===b.id?world.parkTime+dt:0;world.parkId=b.id;if(world.parkTime>2){data().parking[b.id]=true;home.pantry||={};home.pantry.foil=(home.pantry.foil||0)+2;save();sayToast('Discovered '+b.name+' · 2 foil stored at home.');}}else world.parkTime=0;}else world.parkTime=0;}
 const p=target();world.marker.visible=world.label.visible=!!p;if(p){world.marker.position.set(p.x,.02,p.z);world.label.position.set(p.x,1.1,p.z);}
 };
 const disposeBefore=disposeCar77;disposeCar77=function(){endLook();stand();if(car77?.mirrors206)for(const m of car77.mirrors206)m.rt.dispose();return disposeBefore();};
 const clearBefore=clear;clear=function(...args){stand();endLook();world=null;if(car77?.mirrors206){for(const m of car77.mirrors206)m.rt.dispose();car77.mirrors206=null;}return clearBefore(...args);};
 window.motoring206={data,transfer,glovebox,jobs,accept,deliver,parking,destinations,target,ignition,lights,beginLook,endLook,attachCar,seed,relax,stand,restPose,actions,get rest(){return rest;},get world(){return world;}};
})();
