/* Build 269: guided progression, discoveries, contextual Big Rat and single active objective. */
(()=>{
 const state269=()=>{home.flow269=home.flow269||{discovered:{},rewarded:false,intro:false};home.flow269.discovered=home.flow269.discovered||{};return home.flow269;};
 const css=document.createElement('style');css.textContent='#objective269{position:fixed;left:50%;top:58px;transform:translateX(-50%);z-index:34;max-width:min(430px,76vw);padding:7px 13px;border:1px solid #d8c58a66;border-radius:12px;background:#1c342dd9;color:#f3e5bf;font:600 12px/1.3 system-ui;pointer-events:none;box-shadow:0 5px 18px #0004}#objective269 small{display:block;font-weight:400;opacity:.78;margin-top:2px}#discovery269{position:fixed;left:50%;top:22%;transform:translate(-50%,-10px);z-index:70;min-width:230px;max-width:72vw;padding:13px 20px;text-align:center;border:1px solid #d9bc73;border-radius:13px;background:#203a31ee;color:#f8e4b5;font:11px/1.35 system-ui;letter-spacing:.12em;text-transform:uppercase;opacity:0;transition:opacity .25s,transform .25s;pointer-events:none}#discovery269.show{opacity:1;transform:translate(-50%,0)}#discovery269 b{display:block;font:600 21px/1.15 Georgia,serif;letter-spacing:0;text-transform:none;color:#fff2d4;margin-top:4px}body.menu-open65 #objective269,body.photo #objective269,body.cinema #objective269{display:none!important}@media(max-width:600px){#objective269{top:51px;font-size:11px;max-width:70vw;padding:6px 10px}}';document.head.appendChild(css);
 const objective=document.createElement('div');objective.id='objective269';objective.hidden=true;document.body.appendChild(objective);
 const discovery=document.createElement('div');discovery.id='discovery269';document.body.appendChild(discovery);let discoveryTimer=0,lastObjective='';
 function current269(){
  const s=progress76(),f=state269();
  if(!s.missionsActive)return {id:'meet',title:'Meet Big Rat',detail:'Follow the yard path to Big Rat near the north side.'};
  if(!s.vinyl)return {id:'vinyl',title:'Recover the violet-label vinyl',detail:'Follow the torn record sleeves toward the dumpster route.'};
  if(!s.pool)return {id:'pool',title:'Find the silver pool key',detail:'Search around the old pool.'};
  if(!s.jobs)return {id:'return',title:'Return to Big Rat',detail:'Both jobs are complete. Collect your reward.'};
  if(!f.discovered.city)return {id:'city',title:'Explore beyond Pip’s Lane',detail:'The alley route is unlocked. Discover the city entrance.'};
  if(!f.discovered.den)return {id:'den',title:'Find the lizard den',detail:'Explore the west side of the backyard.'};
  if(!home.geckoTamed88)return {id:'lizard',title:'Meet the lizard',detail:'Approach the den and tame your companion.'};
  if(!home.stairwayPortrait183)return {id:'heaven',title:'Find Stairway to Heaven',detail:'Explore the east route and complete the rooftop course.'};
  return {id:'free',title:'Pip’s Lane is yours',detail:'Scavenge, craft, decorate, drive and explore at your own pace.'};
 }
 function drawObjective269(){if(!rat||!['scavenge','house','explore'].includes(phase)){objective.hidden=true;return;}const q=current269(),key=q.id+'|'+q.title;objective.hidden=false;objective.innerHTML=q.title+'<small>'+q.detail+'</small>';if(key!==lastObjective){lastObjective=key;objective.animate?.([{transform:'translateX(-50%) translateY(-5px)',opacity:.5},{transform:'translateX(-50%) translateY(0)',opacity:1}],{duration:260});}}
 function discover269(id,name){const f=state269();if(f.discovered[id])return;f.discovered[id]=true;save();discovery.innerHTML='Location discovered<b>'+name+'</b>';discovery.classList.add('show');discoveryTimer=3.2;const geo=document.getElementById('mapGeo267');if(geo)geo.dataset['found'+id]='1';}
 function proximityDiscover269(){if(phase!=='scavenge'||!rat)return;const p=rat.position;const tests=[['pond','Willow Pond',23.2,32.1,5],['den','Lizard Den',-18.75,24.75,4],['dumpster','The Dumpster',0,-4,8],['bigrat','Big Rat’s Corner',NB.x,NB.z,4],['city','City Entrance',4,38,8],['alley','East Alley Gate',29.5,19,5]];for(const [id,n,x,z,r] of tests)if(Math.hypot(p.x-x,p.z-z)<r)discover269(id,n);}
 function bigRat269(){
  const s=progress76(),f=state269(),ready=s.vinyl&&s.pool;
  if(!s.missionsActive){s.missionsActive=true;f.intro=true;save();modal('Big Rat',`<p><b>“Kid, if you’re staying here, make yourself useful.”</b></p><p>“My violet-label record went missing when the water came through. Follow the torn sleeves toward the dumpster. Bring it back and I’ll show you what’s worth keeping around here.”</p>`,[['Take the job',()=>{closeModal();sayToast('New objective · recover the violet-label vinyl');}],['Not now',closeModal]]);return;}
  if(!s.vinyl){modal('Big Rat',`<p><b>“The record first.”</b></p><p>“Purple label. Old pressing. Follow the torn sleeves toward the dumpster and look up, not just under your paws.”</p>`,[['Show objectives',()=>{closeModal();openObjectives200();}],['Close',closeModal]]);return;}
  if(!s.pool){modal('Big Rat',`<p><b>“Good. One more thing.”</b></p><p>“Silver key. Lost by the old pool. Water carried it somewhere low. Find it and we’re square.”</p>`,[['Track the pool job',()=>{closeModal();sayToast('Current objective · find the silver pool key');}],['Close',closeModal]]);return;}
  if(!s.jobs){modal('Big Rat',`<p><b>“You actually found both.”</b></p><p>“All right. You’ve earned access to the alley route. I put nails and string in your chest too. Don’t waste them.”</p>`,[['Collect reward',()=>{claimJobs76();state269().rewarded=true;save();}],['Close',closeModal]]);return;}
  const lines=[`“City gate’s open. Don’t get flattened.”`,`“The lizard den’s west. Strange little thing, but useful.”`,`“If you hear wings overhead, keep your paws ready.”`,`“Your house still looks half drowned. Do something about it.”`];const line=lines[Math.floor((ensureLife().clock/17)%lines.length)];modal('Big Rat',`<p><b>${line}</b></p><p>Your jobs are done. Explore, build, and come back when you need your bearings.</p>`,[['Objectives',()=>{closeModal();openObjectives200();}],['Close',closeModal]]);
 }
 const talk0=startTalk;startTalk=function(){if(phase==='scavenge'&&yard76?.owner===root)return bigRat269();return talk0();};
 const collect0=collect76;collect76=function(f){const before=progress76()[f.id];const out=collect0(f);if(!before&&f?.id==='vinyl')setTimeout(()=>{if(progress76().vinyl)sayToast('Vinyl recovered · next: search the old pool');},900);if(!before&&f?.id==='pool')setTimeout(()=>{if(progress76().pool)sayToast('Silver key recovered · return to Big Rat');},900);return out;};
 const claim0=claimJobs76;claimJobs76=function(){const ok=claim0();if(ok!==false){const f=state269();f.rewarded=true;save();setTimeout(()=>sayToast('Unlocked · alley route + crafting supplies'),250);}return ok;};
 const objectives0=openObjectives200;openObjectives200=function(){const q=current269(),s=progress76(),f=state269();modal('Objectives',`<div class="objectives200"><section><b>Current</b><p>${q.title}</p><small>${q.detail}</small></section><section><b>Big Rat</b><p>${s.vinyl?'✓':'○'} Recover the violet-label vinyl</p><p>${s.pool?'✓':'○'} Find the silver pool key</p><p>${s.jobs?'✓ Alley route unlocked':'○ Return for reward'}</p></section><section><b>Discoveries</b><p>${Object.keys(f.discovered).length} locations found</p><small>New places are added as Pip reaches them.</small></section></div>`,[['Yard map',()=>openYard201?.()],['Close',closeModal]]);};
 function mapFog269(){const geo=document.getElementById('mapGeo267');if(!geo)return;const f=state269();for(const span of geo.querySelectorAll('span')){const tx=span.textContent.trim().toLowerCase();if(tx==='city')span.style.opacity=f.discovered.city?'1':'.2';if(tx==='den')span.style.opacity=f.discovered.den?'1':'.2';if(tx==='pond')span.style.opacity=f.discovered.pond?'1':'.2';} }
 const tick0=tickWorld38;tickWorld38=function(dt){tick0(dt);drawObjective269();proximityDiscover269();mapFog269();if(discoveryTimer>0){discoveryTimer-=dt;if(discoveryTimer<=0)discovery.classList.remove('show');}};
 window.flow269={current:current269,discover:discover269};
})();