window.classicalRecords227=[
  {
    "id": "record1",
    "title": "Für Elise",
    "composer": "Beethoven",
    "artist": "Sebion7125",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Fur_Elise.ogg",
    "file": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Fur_Elise.ogg",
    "x": -6.1,
    "z": 19.5,
    "clue": "A damp sleeve survived among the sewing scraps.",
    "zone": "yard"
  },
  {
    "id": "record2",
    "title": "Moonlight Sonata · I",
    "composer": "Beethoven",
    "artist": "Bernd Krueger",
    "license": "CC BY-SA 2.0 DE",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/de/",
    "source": "https://commons.wikimedia.org/wiki/File:Beethoven_Moonlight_1st_movement.ogg",
    "file": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Beethoven_Moonlight_1st_movement.ogg",
    "x": 13.1,
    "z": 20.4,
    "clue": "Search the forgotten scraps beyond the old toolbox.",
    "zone": "yard"
  },
  {
    "id": "record3",
    "title": "Clair de lune",
    "composer": "Debussy",
    "artist": "Laurens Goedhart",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg",
    "file": "https://upload.wikimedia.org/wikipedia/commons/b/be/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg",
    "x": 6.7,
    "z": 42.4,
    "clue": "Someone left a sleeve in the city approach’s roadside litter.",
    "zone": "yard"
  },
  {
    "id": "record4",
    "title": "Gymnopédie No. 1",
    "composer": "Satie",
    "artist": "Kevin MacLeod (incompetech.com)",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Gymnopedie_No._1_%28ISRC_USUAN1100787%29.mp3",
    "file": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Gymnopedie_No._1_%28ISRC_USUAN1100787%29.mp3",
    "x": 2.8,
    "z": 53.4,
    "clue": "Past the first city blocks, check the low piles beside the road.",
    "zone": "yard"
  },
  {
    "id": "record5",
    "title": "Canon in D",
    "composer": "Pachelbel",
    "artist": "Kevin MacLeod (incompetech.com)",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Canon_in_D_Major_%28ISRC_USUAN1100301%29.mp3",
    "file": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Canon_in_D_Major_%28ISRC_USUAN1100301%29.mp3",
    "x": 6.6,
    "z": 59,
    "clue": "Before the northern descent, look beneath discarded paper.",
    "zone": "yard"
  },
  {
    "id": "record6",
    "title": "Ode to Joy",
    "composer": "Beethoven",
    "artist": "United States Navy Band",
    "license": "Public domain · US government",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Template:PD-USGov-Military-Navy",
    "source": "https://commons.wikimedia.org/wiki/File:Anthem_of_Europe_%28US_Navy_instrumental_long_version%29.ogg",
    "file": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Anthem_of_Europe_%28US_Navy_instrumental_long_version%29.ogg",
    "x": -10.5,
    "z": 25,
    "clue": "The old maintenance loop kept something dry.",
    "zone": "sewer"
  },
  {
    "id": "record7",
    "title": "Pathétique · Adagio cantabile",
    "composer": "Beethoven",
    "artist": "Daniel Veesey",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Daniel_Veesey_-_02_-_Sonata_8_Pathetique_-_II_Adagio_cantabile.ogg",
    "file": "https://upload.wikimedia.org/wikipedia/commons/0/07/Daniel_Veesey_-_02_-_Sonata_8_Pathetique_-_II_Adagio_cantabile.ogg",
    "x": 13.3,
    "z": 9,
    "clue": "Beyond the eastern bend, a sleeve rests above the muck.",
    "zone": "sewer"
  },
  {
    "id": "record8",
    "title": "Gnossienne No. 1",
    "composer": "Satie",
    "artist": "La Pianista",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Satie_-_Gnossienne_1.ogg",
    "file": "https://upload.wikimedia.org/wikipedia/commons/9/91/Satie_-_Gnossienne_1.ogg",
    "x": -21.3,
    "z": 39,
    "clue": "The distant western canal carries more than water.",
    "zone": "sewer"
  },
  {
    "id": "record9",
    "title": "Arabesque No. 1",
    "composer": "Debussy",
    "artist": "Patrizia Prati",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Claude_Debussy_-_Premi%C3%A8re_Arabesque_-_Patrizia_Prati.ogg",
    "file": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Claude_Debussy_-_Premi%C3%A8re_Arabesque_-_Patrizia_Prati.ogg",
    "x": 17.3,
    "z": 55,
    "clue": "The north-eastern stores have a quiet corner.",
    "zone": "sewer"
  },
  {
    "id": "record10",
    "title": "The Girl with the Flaxen Hair",
    "composer": "Debussy",
    "artist": "Mike Ambrose",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:The_Girl_with_the_Flaxen_Hair.ogg",
    "file": "https://upload.wikimedia.org/wikipedia/commons/c/cb/The_Girl_with_the_Flaxen_Hair.ogg",
    "x": 3.4,
    "z": 63,
    "clue": "The last cistern shelters a forgotten melody.",
    "zone": "sewer"
  }
];
