window.classicalRecords227=[
 {
  "id": "record1",
  "title": "Für Elise",
  "composer": "Beethoven",
  "artist": "Sebion7125",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Fur_Elise.ogg",
  "file": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Fur_Elise.ogg",
  "x": 7,
  "z": 20,
  "clue": "Beside the yard path near 7, 20"
 },
 {
  "id": "record2",
  "title": "Moonlight Sonata · I",
  "composer": "Beethoven",
  "artist": "Bernd Krueger",
  "license": "CC BY-SA 2.0 DE",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/de/",
  "source": "https://commons.wikimedia.org/wiki/File:Beethoven_Moonlight_1st_movement.ogg",
  "file": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Beethoven_Moonlight_1st_movement.ogg",
  "x": 4,
  "z": 35,
  "clue": "Along the city approach, 35 m north"
 },
 {
  "id": "record3",
  "title": "Clair de lune",
  "composer": "Debussy",
  "artist": "Laurens Goedhart",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg",
  "file": "https://upload.wikimedia.org/wikipedia/commons/b/be/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg",
  "x": 4,
  "z": 39,
  "clue": "Along the city approach, 39 m north"
 },
 {
  "id": "record4",
  "title": "Gymnopédie No. 1",
  "composer": "Satie",
  "artist": "Kevin MacLeod (incompetech.com)",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Gymnopedie_No._1_%28ISRC_USUAN1100787%29.mp3",
  "file": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Gymnopedie_No._1_%28ISRC_USUAN1100787%29.mp3",
  "x": 4,
  "z": 43,
  "clue": "Along the city approach, 43 m north"
 },
 {
  "id": "record5",
  "title": "Canon in D",
  "composer": "Pachelbel",
  "artist": "Kevin MacLeod (incompetech.com)",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Canon_in_D_Major_%28ISRC_USUAN1100301%29.mp3",
  "file": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Canon_in_D_Major_%28ISRC_USUAN1100301%29.mp3",
  "x": 4,
  "z": 47,
  "clue": "Along the city approach, 47 m north"
 },
 {
  "id": "record6",
  "title": "Ode to Joy",
  "composer": "Beethoven",
  "artist": "United States Navy Band",
  "license": "Public domain · US government",
  "licenseUrl": "https://commons.wikimedia.org/wiki/Template:PD-USGov-Military-Navy",
  "source": "https://commons.wikimedia.org/wiki/File:Anthem_of_Europe_%28US_Navy_instrumental_long_version%29.ogg",
  "file": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Anthem_of_Europe_%28US_Navy_instrumental_long_version%29.ogg",
  "x": 4,
  "z": 51,
  "clue": "Along the city approach, 51 m north"
 },
 {
  "id": "record7",
  "title": "Pathétique · Adagio cantabile",
  "composer": "Beethoven",
  "artist": "Daniel Veesey",
  "license": "CC0",
  "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Daniel_Veesey_-_02_-_Sonata_8_Pathetique_-_II_Adagio_cantabile.ogg",
  "file": "https://upload.wikimedia.org/wikipedia/commons/0/07/Daniel_Veesey_-_02_-_Sonata_8_Pathetique_-_II_Adagio_cantabile.ogg",
  "x": 4,
  "z": 55,
  "clue": "Along the city approach, 55 m north"
 },
 {
  "id": "record8",
  "title": "Gnossienne No. 1",
  "composer": "Satie",
  "artist": "La Pianista",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Satie_-_Gnossienne_1.ogg",
  "file": "https://upload.wikimedia.org/wikipedia/commons/9/91/Satie_-_Gnossienne_1.ogg",
  "x": 5,
  "z": 60,
  "clue": "Along the city approach, 60 m north"
 },
 {
  "id": "record9",
  "title": "Arabesque No. 1",
  "composer": "Debussy",
  "artist": "Patrizia Prati",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Claude_Debussy_-_Premi%C3%A8re_Arabesque_-_Patrizia_Prati.ogg",
  "file": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Claude_Debussy_-_Premi%C3%A8re_Arabesque_-_Patrizia_Prati.ogg",
  "x": 3.2,
  "z": 28,
  "clue": "Beside the yard path near 3.2, 28"
 },
 {
  "id": "record10",
  "title": "The Girl with the Flaxen Hair",
  "composer": "Debussy",
  "artist": "Mike Ambrose",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:The_Girl_with_the_Flaxen_Hair.ogg",
  "file": "https://upload.wikimedia.org/wikipedia/commons/c/cb/The_Girl_with_the_Flaxen_Hair.ogg",
  "x": 3.2,
  "z": 24,
  "clue": "Beside the yard path near 3.2, 24"
 }
];
