/* A connected sewer district, with collision and map derived from the same floor plan. */
(function(scope){
 function sewerLayout211(){
  const cells=new Set(),rect=(x0,x1,z0,z1)=>{for(let x=x0;x<=x1;x++)for(let z=z0;z<=z1;z++)cells.add(x+','+z);};
  rect(-1,0,0,15);rect(-7,7,6,7);rect(-7,-6,6,13);rect(-7,0,12,13);rect(0,7,4,5);rect(5,7,3,7);rect(0,7,11,12);rect(4,7,10,13);
  const has=(x,z)=>cells.has(x+','+z),inside=(x,z,r=.18)=>{for(const dx of [-r,r])for(const dz of [-r,r])if(!has(Math.floor((x+dx)/2),Math.floor((z+dz)/2)))return false;return true;};
  const walls=[];for(const key of cells){const [x,z]=key.split(',').map(Number);if(!has(x-1,z))walls.push({x:x*2,z:z*2+1,w:.16,d:2});if(!has(x+1,z))walls.push({x:x*2+2,z:z*2+1,w:.16,d:2});if(!has(x,z-1))walls.push({x:x*2+1,z:z*2,w:2,d:.16});if(!has(x,z+1))walls.push({x:x*2+1,z:z*2+2,w:2,d:.16});}
  function resolve(p,before,r=.26){const dx=p.x-before.x,dz=p.z-before.z,n=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.09));let x=before.x,z=before.z;for(let i=1;i<=n;i++){const nx=before.x+dx*i/n,nz=before.z+dz*i/n;if(inside(nx,z,r))x=nx;if(inside(x,nz,r))z=nz;}p.x=x;p.z=z;}
  return {cells,walls,inside,resolve,bounds:[-14,16,0,32]};
 }
 scope.sewerLayout211=sewerLayout211;if(typeof module!=='undefined'){module.exports=sewerLayout211;return;}
 const layout=sewerLayout211(),V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z);
 const entrances=[{id:'yard',label:'Pip’s Lane',surface:V(6.8,0,29.4),below:V(0,0,2.2)},{id:'city',label:'Original city',surface:V(4,0,59),below:V(0,0,29.8)}];
 const caches=[{id:'west',name:'Maintenance crate',x:-11,z:25,item:'nail',count:4},{id:'store',name:'Washed-up bundle',x:13,z:9,item:'cloth',count:3},{id:'pump',name:'Pump-room salvage',x:13,z:25,item:'foil',count:4},{id:'junction',name:'Lost coin',x:-10,z:13,item:'coin',count:1}];
 let state=null,surfaceOwner=null,nearEntrance=null,near=null,restoreLight=null;const surfaceNodes=[];
 const active=()=>phase==='explore'&&area?.id==='sewer211';
 const progress=()=>home.sewer211||(home.sewer211={finds:{}});
 function part(w,h,d,x,y,z,mat,name){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.name=name;m.userData.noInk=true;root.add(m);return m;}
 function label(text,x,y,z,scale=.3){const m=markerText(text);m.position.set(x,y,z);m.scale.setScalar(scale);root.add(m);return m;}
 function surface(){if(phase!=='scavenge'||!root||surfaceOwner===root)return;surfaceOwner=root;surfaceNodes.length=0;
  for(const e of entrances){const g=new THREE.Group();g.name='Sewer entrance · '+e.label;g.position.copy(e.surface);const mat=new THREE.MeshStandardMaterial({color:0x424f46,metalness:.65,roughness:.62});const lid=new THREE.Mesh(new THREE.CylinderGeometry(.58,.58,.035,24),mat);lid.position.y=.022;g.add(lid);for(let i=-2;i<=2;i++){const bar=new THREE.Mesh(new THREE.BoxGeometry(.78,.018,.035),new THREE.MeshStandardMaterial({color:0x899385,roughness:.8}));bar.position.set(0,.05,i*.14);g.add(bar);}root.add(g);const sign=label('↓ SEWER',e.surface.x,1.15,e.surface.z,.25);surfaceNodes.push({g,sign,e});}
 }
 function showMap(){const p=rat?.position||V(),minX=-14,maxZ=32,toX=x=>7+(x+14)/30*86,toZ=z=>94-z/32*86;const tiles=[...layout.cells].map(key=>{const [x,z]=key.split(',').map(Number);return `<rect x="${toX(x*2)}" y="${toZ(z*2+2)}" width="${2/30*86+.1}" height="${2/32*86+.1}" fill="#66877a"/>`;}).join('');const dots=entrances.map(e=>`<circle cx="${toX(e.below.x)}" cy="${toZ(e.below.z)}" r="2" fill="#f1d191"/>`).join('');
  modal('Under Pip’s Lane',`<div class="map201"><svg viewBox="0 0 100 100">${tiles}${dots}${active()?`<circle cx="${toX(p.x)}" cy="${toZ(p.z)}" r="1.7" fill="white" stroke="#17362b" stroke-width=".6"/>`:''}</svg></div><p>Gold: ladders to the yard (south) and city (north). White: Pip.</p><p>West: maintenance loop · East: storeroom and pump chamber. Follow the warm lights back to a ladder.</p><p>Salvage found: ${Object.keys(progress().finds||{}).length} / ${caches.length}</p>`,[['Close',closeModal]]);
 }
 function enter(id='yard'){
  if(car77?.riding)return sayToast('Park and leave the car before climbing down.');if(rat?.userData.geckoRide88||rat?.userData.bird71)return sayToast('Dismount before climbing down.');
  const entry=entrances.find(e=>e.id===id)||entrances[0];exitPhoto();closeModal();window.touring209?.toggleFoot(false);phase='explore';clear();sc=null;area={id:'sewer211',items:[],obstacles:[],near:null,exit:false};
  sfx.rain(false);radioStop();$('radioui').style.display='none';ui.hb.style.display=ui.go.style.display=ui.talk.style.display=ui.prompt.style.display='none';ui.title.style.display='none';ui.pad.style.display=matchMedia('(pointer:coarse)').matches?'flex':'none';ui.phase.textContent='Underground · Old sewers';
  restoreLight={sun:sun.intensity,hemi:hemi.intensity};scene.background.set(0x101c1b);scene.fog=new THREE.Fog(0x101c1b,9,30);sun.intensity=.15;hemi.intensity=.8;
  state={owner:root,water:[],finds:[],clock:0};const wall=MT(0x64726a,'brick',1,1),floor=MT(0x8c8972,'cobble',1,1),metal=new THREE.MeshStandardMaterial({color:0x59695c,roughness:.7,metalness:.5}),rust=new THREE.MeshStandardMaterial({color:0x765b39,roughness:.9}),trim=new THREE.MeshStandardMaterial({color:0x627769,roughness:.9});
  // One instanced floor and one instanced wall set keep the underground map light on phones.
  const floors=new THREE.InstancedMesh(new THREE.BoxGeometry(2,.12,2),floor,layout.cells.size),dummy=new THREE.Object3D();let i=0;for(const key of layout.cells){const [x,z]=key.split(',').map(Number);dummy.position.set(x*2+1,-.065,z*2+1);dummy.updateMatrix();floors.setMatrixAt(i++,dummy.matrix);}floors.name='Sewer stone floor';root.add(floors);const roof=floors.clone();roof.name='Sewer ceiling';roof.position.y=2.94;root.add(roof);
  const walls=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),wall,layout.walls.length);layout.walls.forEach((p,i)=>{dummy.position.set(p.x,1.4,p.z);dummy.scale.set(p.w,2.8,p.d);dummy.updateMatrix();walls.setMatrixAt(i,dummy.matrix);});walls.name='Sewer brick walls';root.add(walls);registerSolid62(walls);
  // Shallow water in the central channel leaves a clear stone walkway on either side.
  const waterMat=new THREE.MeshPhongMaterial({color:0x315f56,transparent:true,opacity:.72,shininess:65,side:THREE.DoubleSide});const water=new THREE.Mesh(new THREE.PlaneGeometry(.75,30),waterMat);water.rotation.x=-Math.PI/2;water.position.set(0,.007,16);water.name='Shallow sewer channel';root.add(water);state.water.push(water);
  for(const x of [-.45,.45])part(.09,.08,30,x,.005,16,trim,'Channel edge');
  for(const z of [3,9,15,21,27,31]){const arch=new THREE.Mesh(new THREE.TorusGeometry(1.82,.065,5,18,Math.PI),trim);arch.position.set(0,.9,z);arch.name='Brick arch rib';root.add(arch);for(const x of [-1.82,1.82])part(.13,.9,.13,x,.45,z,trim,'Arch foot');}
  for(const [x,z]of [[-1.65,6],[-1.65,18],[-12,14],[-12,25],[13,10],[13,24],[1.65,29]]){const lamp=part(.2,.28,.16,x,1.8,z,new THREE.MeshBasicMaterial({color:0xf8ce83}),'Sewer wall lamp');const glow=new THREE.PointLight(0xffcf8a,.65,6,2);glow.position.set(x,1.7,z);root.add(glow);}
  for(const x of [-1.72,1.72]){const pipe=new THREE.Mesh(new THREE.CylinderGeometry(.09,.09,30,8),rust);pipe.rotation.x=Math.PI/2;pipe.position.set(x,2.1,16);pipe.name='Overhead sewer pipe';root.add(pipe);}
  // Both exits are real, reachable ladder interactions, without keys or mission gates.
  for(const e of entrances){const z=e.id==='yard'?.4:31.6;for(const x of [-.38,.38])part(.055,2.5,.055,x,1.25,z,metal,'Surface ladder rail');for(let y=.2;y<2.5;y+=.24)part(.8,.045,.05,0,y,z,metal,'Surface ladder rung');label('↑ '+e.label,0,2.25,z,e.id==='yard'?.25:.3);const grate=new THREE.Mesh(new THREE.CircleGeometry(.6,20),metal);grate.rotation.x=Math.PI/2;grate.position.set(0,2.7,z);root.add(grate);}
  label('MAINTENANCE ←',-3,1.9,14,.26);label('PUMP ROOM →',3,1.9,24,.26);label('STOREROOM →',3,1.9,10,.26);
  const pump=part(1.4,1.2,1.1,14, .6,26,metal,'Old pump');registerSolid62(pump);const valve=new THREE.Mesh(new THREE.TorusGeometry(.32,.05,6,18),rust);valve.position.set(13.25,.8,26);valve.rotation.y=Math.PI/2;root.add(valve);
  progress().finds||={};for(const f of caches){if(progress().finds[f.id])continue;const m=ITEMS[f.item].build();m.position.set(f.x,.04,f.z);m.name=f.name;root.add(m);const mark=label('✦',f.x,.65,f.z,.17);state.finds.push({...f,m,mark});}
  rat=makeRat();rat.scale.setScalar(.25);rat.position.copy(entry.below);rat.rotation.y=id==='yard'?0:Math.PI;root.add(rat);outline(rat);gameCam.yaw=id==='yard'?Math.PI:0;gameCam.pitch=.32;gameCam.distance=2.3;gameCam.phase='explore';gameCam.ready=false;bag();save();sayToast('Old sewers · explore the tunnels. Gold ladders lead back outside.');
 }
 function exit(id){const e=entrances.find(e=>e.id===id)||entrances[0];closeModal();startScavenge();rat.position.copy(e.surface).add(V(0,0,id==='yard'?-1.2:1.2));rat.userData.air=false;rat.userData.vy=0;gameCam.ready=false;sayToast('Back in '+e.label);}
 function tick(dt){if(!active()||!state)return;state.clock+=dt;const speed=control(dt,{walk:2.3,bounds:layout.bounds,ground:()=>0});rat.animate(dt,speed,false);steps(dt,speed,'cobble');near=null;let distance=1.5;
  for(const e of entrances){const d=rat.position.distanceTo(e.below);if(d<distance){near={kind:'exit',entry:e};distance=d;}}
  for(const f of state.finds){if(!f.m.visible)continue;f.mark.position.y=.65+Math.sin(state.clock*2)*.04;const d=rat.position.distanceTo(f.m.position);if(d<1&&d<distance){near={kind:'find',find:f};distance=d;}}
  ui.prompt.style.display=near?'block':'none';ui.prompt.textContent=near?.kind==='exit'?'Climb to '+near.entry.label:near?'Collect '+near.find.name:'';$('padE').textContent=near?.kind==='exit'?'Climb out':'Grab';ui.go.style.display='none';
 }
 const oldTick=tickArea;tickArea=function(dt){if(active())return tick(dt);return oldTick(dt);};
 const oldResolve=resolveGeometry62;resolveGeometry62=function(p,before){oldResolve(p,before);if(active())layout.resolve(p,before);};
 const oldGrab=grab;grab=function(){if(!gameplayActive())return oldGrab();if(active()){if(near?.kind==='exit')return exit(near.entry.id);if(near?.kind==='find'){const f=near.find;if(progress().finds[f.id])return;if(totalBag()+f.count>bagCapacity())return sayToast('Make room in your bag first.');inv[f.item]=(inv[f.item]||0)+f.count;progress().finds[f.id]=true;f.m.visible=f.mark.visible=false;near=null;bag();save();sfx.pickup();sayToast(f.count+' '+ITEMS[f.item].name+' collected.');}return;}if(nearEntrance)return enter(nearEntrance.id);return oldGrab();};
 const beforeWorld=tickWorld38;tickWorld38=function(dt){beforeWorld(dt);if(phase==='scavenge'){surface();nearEntrance=null;if(gameplayActive()&&!car77?.riding&&!rat.userData.geckoRide88)nearEntrance=entrances.find(e=>rat.position.distanceTo(e.surface)<1.2)||null;if(nearEntrance){ui.prompt.style.display='block';ui.prompt.textContent='Enter the underground sewer';$('padE').textContent='Sewer';}}else nearEntrance=null;if(active()){$('weatherBadge').textContent='Underground';sun.intensity=.15;hemi.intensity=.8;}mapButton.hidden=!active()||!gameplayActive();};
 const oldCamera=tickGameplayCamera;tickGameplayCamera=function(dt){if(!active()||photo.active||window.touring209?.firstPerson)return oldCamera(dt);$('cameraTools').style.display='none';const target=rat.position.clone().add(V(0,.35,0)),direction=V(Math.sin(gameCam.yaw)*Math.cos(gameCam.pitch),Math.sin(gameCam.pitch),Math.cos(gameCam.yaw)*Math.cos(gameCam.pitch));const ray=new THREE.Raycaster(target,direction,0,2.6),hits=ray.intersectObjects(solidMeshes62(),false),dist=hits.length?Math.max(.38,Math.min(2.3,hits[0].distance-.15)):2.3;camera.position.copy(target).addScaledVector(direction,dist);camera.position.y=Math.min(2.5,camera.position.y);camera.lookAt(target);};
 const oldMap=openMap;openMap=function(){if(active())return showMap();oldMap();if($('modal').style.display==='flex'){const b=document.createElement('button');b.className='btn';b.textContent='Sewer entrances';b.onclick=()=>modal('Sewer entrances','<p>Look for the round iron cover beside the north-yard path, or the cover just inside the original city. Walk up and press Sewer to climb down.</p>',[['Sewer map',showMap],['Close',closeModal]]);$('modalActions').appendChild(b);}};
 const oldActions=motoring206.actions;motoring206.actions=function(){if(active()){modal('Pip’s actions','<p>Explore the tunnels and collect salvage. Climb a marked ladder to return to the surface.</p>',[['Sewer map',showMap],['Close',closeModal]]);return;}oldActions();};$('pipActions205').onclick=()=>motoring206.actions();
 const mapButton=document.createElement('button');mapButton.id='sewerMap211';mapButton.textContent='Sewer map';mapButton.hidden=true;mapButton.onclick=showMap;document.body.appendChild(mapButton);const css=document.createElement('style');css.textContent='#sewerMap211{position:fixed;right:12px;top:200px;z-index:48;min-height:44px;padding:8px 12px;border:1px solid #d4d9ba44;border-radius:12px;background:#20372ddd;color:#f2e6c9;font:600 12px system-ui}#sewerMap211[hidden]{display:none!important}@media(max-height:520px){#sewerMap211{top:64px}}';document.head.appendChild(css);
 const oldClear=clear;clear=function(...args){if(restoreLight){sun.intensity=restoreLight.sun;hemi.intensity=restoreLight.hemi;restoreLight=null;}state=null;near=null;nearEntrance=null;return oldClear(...args);};
 scope.sewer211={enter,exit,showMap,layout,entrances,get active(){return active();},get state(){return state;}};
})(typeof window==='undefined'?globalThis:window);
