/* Original 68 BPM gondola lullaby, rendered once to PCM and played by the game's unlocked music element. */
(function(scope){
 function renderSewer218(){const rate=22050,beat=60/68,melody=[64,null,67,69,null,67,64,null,62,60,null,null,62,null,65,67,null,65,62,null,60,59,null,null,60,null,64,67,null,64,62,null,60,59,null,null,62,null,65,64,null,62,60,null,59,60,null,null],length=Math.ceil(melody.length*beat*rate),samples=new Float32Array(length);
 function note(midi,start,duration,level,reed){const f=440*2**((midi-69)/12),offset=Math.floor(start*rate),n=Math.floor(duration*rate);for(let i=0;i<n&&offset+i<length;i++){const t=i/rate,attack=Math.min(1,t/(reed?.25:.015)),env=reed?attack*Math.max(0,1-t/duration)**1.7:attack*Math.exp(-t*3.1),wave=Math.sin(2*Math.PI*f*t)+Math.sin(4*Math.PI*f*t)*(reed?.12:.22)+Math.sin(6*Math.PI*f*t)*.045;samples[offset+i]+=wave*env*level;}}
 melody.forEach((n,i)=>{if(n!==null)note(n,i*beat,beat*1.8,.7,false);if(i%6===0)for(const m of [[48,52,55],[47,50,55],[45,48,52],[43,47,50]][Math.floor(i/12)%4])note(m,i*beat,beat*5.7,.12,true);});let peak=0;for(const s of samples)peak=Math.max(peak,Math.abs(s));const buffer=new ArrayBuffer(44+length*2),d=new DataView(buffer),str=(p,s)=>{for(let i=0;i<s.length;i++)d.setUint8(p+i,s.charCodeAt(i));};str(0,'RIFF');d.setUint32(4,36+length*2,true);str(8,'WAVEfmt ');d.setUint32(16,16,true);d.setUint16(20,1,true);d.setUint16(22,1,true);d.setUint32(24,rate,true);d.setUint32(28,rate*2,true);d.setUint16(32,2,true);d.setUint16(34,16,true);str(36,'data');d.setUint32(40,length*2,true);for(let i=0;i<length;i++){const edge=Math.min(1,i/(rate*.25),(length-i)/(rate*.4));d.setInt16(44+i*2,Math.round(samples[i]/peak*.72*edge*32767),true);}return buffer;}
 if(typeof module!=='undefined'){module.exports=renderSewer218;return;}
 let url=null,saved=null,player=null,pending=false,blocked=false,generation=0;const active=()=>phase==='explore'&&area?.id==='sewer211';
 const button=document.createElement('button');button.id='sewerAudio218';button.textContent='♫ Tap for sewer music';button.hidden=true;button.style.cssText='position:fixed;right:12px;top:252px;z-index:70;padding:10px 12px;border-radius:12px;background:#e4c997;color:#243b31;border:0;font:600 12px system-ui';document.body.appendChild(button);
 function enter(){if(saved)return;const el=musicElement69();if(!el.src)setTrack69();saved={src:el.getAttribute('src')||el.src,time:el.currentTime||0,loop:el.loop};player=el;generation++;pending=blocked=false;el.pause();url||=URL.createObjectURL(new Blob([renderSewer218()],{type:'audio/wav'}));el.src=url;el.loop=true;el.volume=0;$('pianoToggle').textContent='Sewer · Quiet gondola';tick(.016);}
 function tick(dt=.016){if(!active())return;if(!saved)enter();const el=player;if(!el)return;const allowed=piano.enabled&&voiceOn&&!document.hidden;if(!allowed){el.pause();button.hidden=true;return;}el.volume=Math.min(.22,el.volume+Math.min(dt,.1)*.12);if(el.paused&&!pending&&!blocked){pending=true;const token=generation;Promise.resolve(el.play()).then(()=>{if(token!==generation)return;pending=false;button.hidden=true;if(!active()||!piano.enabled||!voiceOn||document.hidden)el.pause();},()=>{if(token!==generation)return;pending=false;blocked=true;button.hidden=false;});}button.hidden=!blocked;}
 function leave(){generation++;pending=blocked=false;button.hidden=true;if(!saved)return;const old=saved; saved=null;player.pause();player.src=old.src;player.loop=old.loop;try{player.currentTime=old.time;}catch{}player.volume=music69.volume;player=null;$('pianoToggle').textContent=music69.tracks[music69.index]?.title||'Music';music69.pending=false;music69.blocked=false;}
 button.onclick=()=>{piano.enabled=true;voiceOn=true;blocked=false;tick();};document.addEventListener('pointerdown',()=>{if(active()&&blocked){blocked=false;tick();}},{passive:true});
 scope.sewerAudio218={enter,tick,leave,get active(){return active();},get playing(){return !!player&&!player.paused;}};
})(typeof window==='undefined'?globalThis:window);
