/* Canoe, canals, water effects and an original accordion-style sewer waltz. */
(function(){
 const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),channels=[[-1.1,1.1,3,66],[-22,23,37,39.2],[-22,-20,25,52],[-21,0,49,51],[19,21,25,56],[0,21,53,55],[-5,5,61,65],[11,19,35,43]];
 const wet=(x,z)=>channels.some(([a,b,c,d])=>x>a&&x<b&&z>c&&z<d),ground=(x,z)=>wet(x,z)?.02:.34;
 let boat=null,layout=null,riding=false,time=0,speed=0,stroke=-1,wake=0,effects=[],flows=[],audio=null,nextNote=0,noteIndex=0,music=true,owner=null;const ringGeo=new THREE.RingGeometry(.8,1,20),dropGeo=new THREE.SphereGeometry(.015,5,4);
 function effect(kind,p,vel){if(effects.length>100)return;const m=new THREE.Mesh(kind==='drop'?dropGeo:ringGeo,new THREE.MeshBasicMaterial({color:0x91b5a4,transparent:true,opacity:.35,side:THREE.DoubleSide,depthWrite:false}));m.position.copy(p);if(kind!=='drop'){m.rotation.x=-Math.PI/2;m.position.y=.306;m.scale.setScalar(.03);}root.add(m);effects.push({m,kind,vel,age:0,life:kind==='drop'?.65:2});}
 function buildWater(plan){layout=plan;const dry=[],water=[];for(const key of plan.cells){const [cx,cz]=key.split(',').map(Number);for(let i=0;i<4;i++)for(let j=0;j<4;j++){const x=cx*2+.25+i*.5,z=cz*2+.25+j*.5;(wet(x,z)?water:dry).push([x,z]);}}
 const dummy=new THREE.Object3D();for(const [arr,geo,mat,y,name]of [[dry,new THREE.BoxGeometry(.5,.34,.5),MT(0x726e58,'cobble',1,1),.17,'Raised sewer walkways'],[water,new THREE.PlaneGeometry(.5,.5),new THREE.MeshPhongMaterial({color:0x244e40,transparent:true,opacity:.83,shininess:75,side:THREE.DoubleSide}),.3,'Deep sewer canals']]){const mesh=new THREE.InstancedMesh(geo,mat,arr.length);arr.forEach(([x,z],i)=>{dummy.position.set(x,y,z);dummy.rotation.set(name==='Deep sewer canals'?-Math.PI/2:0,0,0);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});mesh.name=name;root.add(mesh);}
 }
 function decor(){const metal=new THREE.MeshStandardMaterial({color:0x62583e,roughness:.85}),brick=MT(0x596247,'brick',1,1);function box(w,h,d,x,y,z,mat,name){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.name=name;root.add(m);return m;}
 // Outfalls approach the water from both banks, plus an overhead broken pipe.
 for(const [x,z,dx,dz,r]of [[-1.7,11,1,0,.22],[1.7,21,-1,0,.16],[-1.7,43,1,0,.3],[8,36.4,0,1,.24],[16,39.8,0,-1,.18],[20,47,0,0,.28]]){const start=V(x,1.5,z),end=start.clone().add(V(dx*.85,-1.18,dz*.85)),pipe=new THREE.Mesh(new THREE.CylinderGeometry(r,r,.7,12,1,true),metal);pipe.material=metal.clone();pipe.material.side=THREE.DoubleSide;pipe.quaternion.setFromUnitVectors(V(0,1,0),V(dx,-.3,dz).normalize());pipe.position.copy(start);root.add(pipe);const curve=new THREE.QuadraticBezierCurve3(start,start.clone().add(V(dx*.8,-.1,dz*.8)),end),stream=new THREE.Mesh(new THREE.TubeGeometry(curve,10,r*.65,6,false),new THREE.MeshPhongMaterial({color:0x5d9980,transparent:true,opacity:.55}));root.add(stream);flows.push({stream,end,seed:z});}
 for(let i=0;i<35;i++){const keys=[...layout.cells],key=keys[(i*31)%keys.length],[cx,cz]=key.split(',').map(Number),x=cx*2+.45,z=cz*2+.5;if(wet(x,z)||Math.hypot(x,z-2.2)<3||Math.hypot(x,z-29.8)<3)continue;const size=.12+(i%5)*.065;let m;if(i%4===0){m=new THREE.Mesh(new THREE.CylinderGeometry(size,size*.85,size*2,10),metal);m.position.set(x,.34+size,z);m.name='Discarded drain tin';}else if(i%4===1){m=new THREE.Mesh(new THREE.TorusGeometry(size,.05,6,12),metal);m.rotation.x=Math.PI/2;m.position.set(x,.41,z);m.name='Discarded rubber ring';}else{m=box(size*2,size,size*1.2,x,.34+size/2,z,brick,i%2?'Loose brick':'Broken masonry');}if(!m.parent)root.add(m);if(size>.25)registerSolid62(m);}
 for(const [x,z]of [[-21,38],[-21,50],[21,38],[19,54],[0,62],[12,36],[0,48]]){const g=new THREE.PointLight(0xe9bd77,.7,9,2);g.position.set(x,2,z);root.add(g);box(.16,.22,.16,x,2.15,z,new THREE.MeshBasicMaterial({color:0xd7b879}),'Old maintenance lamp');}
 }
 function init(entry,plan){layout=plan;owner=root;boat=makeCanoe212();boat.scale.setScalar(.8);boat.position.set(0,.204,entry.id==='city'?33:5);boat.rotation.y=entry.id==='city'?Math.PI:0;root.add(boat);boat.name='Rowable sewer canoe';riding=false;time=0;stroke=-1;speed=0;rat.position.y=ground(rat.position.x,rat.position.z);decor();const sign=markerText('CANOE · BOARD');sign.position.copy(boat.position).add(V(0,1.1,0));sign.scale.setScalar(.25);root.add(sign);boat.userData.sign=sign;startMusic();}
 function startMusic(){window.sewerAudio218?.enter();}
 function musicTick(){window.sewerAudio218?.tick();}

 function pose(){const u=rat.userData,b=u.pipBones;if(!b?.Hips)return;for(const [name,q]of Object.entries(u.pipRest))if(b[name])b[name].quaternion.copy(q);for(const side of ['Left','Right']){b[side+'UpLeg']?.rotateX(-1.15);b[side+'Leg']?.rotateX(1.05);}const phase=time*2.4%(Math.PI*2),drive=phase<Math.PI,paddle=boat.userData.paddle;paddle.position.set(.015,.58+(drive?0:.02*Math.sin(phase-Math.PI)),.065+.025*Math.cos(phase));paddle.rotation.set(.25*Math.cos(phase),0,.9+(drive?0:.35*Math.sin(phase-Math.PI)));b.Spine?.rotateX(.09*Math.sin(phase));rat.rotation.y=boat.rotation.y;rat.updateWorldMatrix(true,true);boat.updateWorldMatrix(true,true);rat.position.add(boat.localToWorld(V(0,.365,-.1)).sub(b.Hips.getWorldPosition(V())));rat.updateWorldMatrix(true,true);for(const [side,y]of [['Left',-.055],['Right',.055]])solveArm203(THREE,rat,side,paddle.localToWorld(V(0,y,0)));}
 function canFloat(p,yaw){for(const x of [-.31,.31])for(const z of [-.74,0,.74]){const q=V(x,0,z).applyAxisAngle(V(0,1,0),yaw).add(p);if(!layout.inside(q.x,q.z,.12)||!wet(q.x,q.z))return false;}return true;}
 function tick(dt){if(!boat||owner!==root)return false;musicTick();for(const f of flows){f.stream.material.opacity=.48+Math.sin(t*5+f.seed)*.07;if(Math.random()<dt*5)effect('ripple',f.end);}
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.age+=dt;if(e.age>e.life){root.remove(e.m);e.m.material.dispose();effects.splice(i,1);continue;}e.m.material.opacity=.3*(1-e.age/e.life);if(e.kind==='drop'){e.vel.y-=dt*1.3;e.m.position.addScaledVector(e.vel,dt);if(e.m.position.y<.3)e.m.visible=false;}else{e.m.scale.setScalar(.03+e.age*.19);if(e.vel)e.m.position.addScaledVector(e.vel,dt);}}
 if(!riding)return false;if(!gameplayActive()){speed=0;pose();return true;}const thrust=(keys.w||keys.arrowup?1:keys.s||keys.arrowdown?-1:Math.abs(joy.z)>.15?-joy.z:0),steer=(keys.d||keys.arrowright?1:keys.a||keys.arrowleft?-1:Math.abs(joy.x)>.15?joy.x:0),yaw=boat.rotation.y-steer*dt*1.25;if(canFloat(boat.position,yaw))boat.rotation.y=yaw;speed=THREE.MathUtils.damp(speed,thrust*1.7,3,dt);const next=boat.position.clone().addScaledVector(V(Math.sin(boat.rotation.y),0,Math.cos(boat.rotation.y)),speed*dt);if(canFloat(next,boat.rotation.y))boat.position.copy(next);else speed=0;rat.userData.air=false;rat.userData.vy=0;rat.userData.act=null;rat.userData.vel=0;rat.animate(dt,0,false);if(Math.abs(speed)>.05)time+=dt*Math.max(.45,Math.abs(speed));pose();boat.userData.sign.visible=false;
 if(Math.abs(speed)>.1){const current=Math.floor(time*2.4/(Math.PI*2));if(current!==stroke){stroke=current;const hit=boat.userData.paddle.localToWorld(V(0,-.75,0));hit.y=.305;effect('ripple',hit);for(let i=0;i<7;i++)effect('drop',hit,V(Math.cos(i*2)*.18,.25+i*.025,Math.sin(i*2)*.18));}if((wake+=dt)>.2){wake=0;for(const x of [-.18,.18])effect('ripple',boat.localToWorld(V(x,.12,-.95)),V(x*.2,0,-.1).applyAxisAngle(V(0,1,0),boat.rotation.y));}}
 ui.prompt.style.display='block';ui.prompt.textContent='Canoe · forward/back to row · left/right to steer';$('padE').textContent='Leave boat';ui.go.style.display='none';return true;}
 function hint(){if(boat&&!riding&&rat.position.distanceTo(boat.position)<2){$('padE').textContent='Board';ui.prompt.style.display='block';ui.prompt.textContent='Board the sewer canoe';}}
 function grab(){if(!boat)return false;if(riding){for(const radius of [1.25,1.75,2.25])for(let i=0;i<16;i++){const p=boat.position.clone().add(V(Math.sin(i*Math.PI/8)*radius,0,Math.cos(i*Math.PI/8)*radius));if(!layout.inside(p.x,p.z,.28)||wet(p.x,p.z))continue;p.y=.34;const before=p.clone();resolveGeometry62(p,before);riding=false;document.body.classList.remove('canoe215');rat.userData.canoe215=false;rat.position.copy(p);rat.userData.air=false;rat.userData.vy=0;rat.userData.motionX=rat.userData.motionZ=0;speed=0;boat.userData.sign.position.copy(boat.position).add(V(0,1.1,0));boat.userData.sign.visible=true;return true;}sayToast('Row closer to a dry bank to leave the canoe.');return true;}
 if(rat.position.distanceTo(boat.position)>=2)return false;touring209?.toggleFoot(false);riding=true;document.body.classList.add('canoe215');rat.userData.canoe215=true;rat.userData.air=false;rat.userData.act=null;rat.userData.job67=null;gameCam.pitch=.45;pose();return true;}
 function clear(){window.sewerAudio218?.leave();document.body.classList.remove('canoe215');riding=false;boat=null;owner=null;flows=[];for(const e of effects)e.m.material.dispose();effects=[];}
 const css=document.createElement('style');css.textContent='body.canoe215 #padB,body.canoe215 #padR,body.canoe215 #padJ,body.canoe215 #padC,body.canoe215 #footView209{display:none!important}';document.head.appendChild(css);
 const oldWorld=tickWorld38;tickWorld38=function(dt){oldWorld(dt);const map=$('miniMap171');if(phase!=='scavenge'||!map)return;for(const [id,x,z]of [['yard',6.8,29.4],['city',4,59]]){let m=map.querySelector('[data-sewer215="'+id+'"]');if(!m){m=document.createElement('i');m.dataset.sewer215=id;m.textContent='↓ SEWER';m.title='Sewer '+id+' entrance';m.style.cssText='position:absolute;color:#ffe19c;background:#203b35dd;font:700 8px system-ui;padding:2px;border-radius:3px;z-index:4;transform:translate(-50%,-50%);pointer-events:none';map.appendChild(m);}mapPoint171(m,x,z);}}
 window.sewerBoat215={buildWater,init,tick,hint,grab,ground,clear,wet,canFloat,toggleMusic(){piano.enabled=!piano.enabled;musicTick();syncMusicMute192();sayToast('Sewer music '+(piano.enabled?'on':'off'));},get boat(){return boat;},get riding(){return riding;}};
})();
