(()=>{
 const $=id=>document.getElementById(id),stage=$('stage'),V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),scene=new THREE.Scene();scene.background=new THREE.Color(0x203b32);
 let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch(e){$('status').textContent='3D could not start. Open in Chrome and reload.';return;}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputEncoding=THREE.sRGBEncoding;stage.prepend(renderer.domElement);
 const camera=new THREE.PerspectiveCamera(45,1,.005,50);scene.add(new THREE.HemisphereLight(0xffefcd,0x4b6356,1.5));const lamp=new THREE.DirectionalLight(0xffffff,1.7);lamp.position.set(2,4,-3);scene.add(lamp);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x344b3f,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.005;scene.add(ground);
 const car=createRoadster202(THREE);scene.add(car);let seated,standing,actor,bodies=[],footBodies=[],poseClock=0,smoke=createPipSmoke227(THREE,scene),mode='car',first=false,paused=false,headphones=null,wear=false,yaw=-.75,pitch=.23,distance=1.6;
 function reset(){yaw=first?0:-.75;pitch=first?.15:.23;distance=mode==='car'?Math.max(1.55,1.0/camera.aspect):Math.max(.9,.6/camera.aspect);}
 function choose(m){smoke.stop();mode=m;first=false;actor=m==='car'?seated:standing;if(!actor)return;car.visible=m==='car';seated.model.visible=m==='car';standing.model.visible=m==='foot';$('car').classList.toggle('active',m==='car');$('foot').classList.toggle('active',m==='foot');$('first').classList.remove('active');$('smoke').textContent='Light cigarette';reset();}
 function fit(asset){const model=asset.scene,bones={};scene.add(model);const mixer=new THREE.AnimationMixer(model);mixer.clipAction(asset.animations.find(a=>a.name==='Idle_4')).play();mixer.update(0);const bounds=new THREE.Box3().setFromObject(model);model.scale.setScalar(.5/(bounds.max.y-bounds.min.y));model.position.y=-bounds.min.y*model.scale.x;model.traverse(o=>{if(o.isBone)bones[o.name]=o;});model.updateMatrixWorld(true);const f=bones.headfront.getWorldPosition(V()).sub(bones.Head.getWorldPosition(V()));model.rotation.y=-Math.atan2(f.x,f.z);const rest={};for(const [n,b]of Object.entries(bones))rest[n]=b.quaternion.clone();return {model,bones,update(){for(const [n,b]of Object.entries(bones))b.quaternion.copy(rest[n]);}};}
 const loader=new THREE.GLTFLoader();loader.load('rat-animation-pack67.glb',asset=>{const mixer=new THREE.AnimationMixer(asset.scene);mixer.clipAction(asset.animations.find(a=>a.name==='Idle_4')).play();mixer.update(0);seated=createPipDrivingStudy(asset.scene,car,{fast:true});seated.model.traverse(m=>{if(m.isSkinnedMesh)bodies.push(createStudyInsideBody(THREE,m));});loader.load('rat-animation-pack67.glb',a=>{standing=fit(a);standing.model.traverse(m=>{if(m.isSkinnedMesh)footBodies.push(createStudyInsideBody(THREE,m));});headphones=createPipHeadphones227(THREE);scene.add(headphones);choose('car');$('status').textContent='Tap Light cigarette to test lighting, holding, drawing and exhaling.';window.smokingStudy227={seated,standing,smoke,choose,camera,scene};});},undefined,()=>{$('status').textContent='Model failed to load. Reload to retry.';});
 $('car').onclick=()=>choose('car');$('foot').onclick=()=>choose('foot');$('first').onclick=()=>{first=!first;$('first').classList.toggle('active',first);reset();};$('smoke').onclick=()=>{if(!actor)return;if(smoke.active)smoke.stop();else smoke.start();$('smoke').textContent=smoke.active?'Put out':'Light cigarette';};$('headset').onclick=()=>{wear=!wear;$('headset').classList.toggle('active',wear);};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause';};$('reset').onclick=reset;
 function resize(){camera.aspect=stage.clientWidth/stage.clientHeight;renderer.setSize(stage.clientWidth,stage.clientHeight);camera.updateProjectionMatrix();reset();}new ResizeObserver(resize).observe(stage);resize();
 const pointers=new Map();let pinch=0;const el=renderer.domElement;el.onpointerdown=e=>{el.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});};el.onpointermove=e=>{const old=pointers.get(e.pointerId);if(!old)return;const dx=e.clientX-old.x,dy=e.clientY-old.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){yaw-=dx*.005;pitch=THREE.MathUtils.clamp(pitch+dy*.004,-.4,1.3);}else{const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch)distance=THREE.MathUtils.clamp(distance*pinch/d,.35,4);pinch=d;}};el.onpointerup=el.onpointercancel=e=>{pointers.delete(e.pointerId);pinch=0;};
 const clock=new THREE.Clock();function frame(){requestAnimationFrame(frame);const dt=Math.min(.05,clock.getDelta());if(actor){poseClock+=dt;if(!paused&&poseClock>=1/24){const step=poseClock;poseClock=0;[...bodies,...footBodies].forEach(b=>b.mesh.geometry=b.full);actor.update(0);if(smoke.active)smoke.pose(actor.model,actor.bones,mode==='car'?car:actor.model,step,mode==='car');(mode==='car'?bodies:footBodies).forEach(b=>b.sync(false));}bodies.forEach(b=>b.mesh.geometry=first&&mode==='car'?b.inside:b.full);footBodies.forEach(b=>b.mesh.geometry=first&&mode==='foot'?b.inside:b.full);
  const head=actor.bones.Head.getWorldPosition(V());if(headphones){headphones.visible=wear&&!first;const forward=actor.bones.headfront.getWorldPosition(V()).sub(head).normalize(),right=V().crossVectors(V(0,1,0),forward).normalize(),up=V().crossVectors(forward,right);headphones.position.copy(head).addScaledVector(up,.022).addScaledVector(forward,-.008);headphones.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(right,up,forward));}
  if(first){camera.position.copy(head).add(V(0,.022,.025));camera.fov=85;camera.lookAt(camera.position.clone().add(V(Math.sin(yaw)*Math.cos(pitch),-Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch))));}else{camera.fov=45;const target=mode==='car'?V(-.12,.35,-.12):V(0,.26,0);camera.position.copy(target).add(V(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance));camera.lookAt(target);}camera.updateProjectionMatrix();}renderer.render(scene,camera);
 }frame();
})();
