/* Pip cigarette gesture: actual arm bones, reusable props and a bounded smoke pool. */
(()=>{
 let state=null,headPose=null;
 function restoreHeadPose(){if(headPose){headPose.bone.quaternion.copy(headPose.quaternion);headPose=null;}}const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),ease=x=>{x=THREE.MathUtils.clamp(x,0,1);return x*x*(3-2*x);};
 function eligible(){const u=rat?.userData;return u&&u.pipBones?.LeftHand&&['scavenge','house','inside','explore'].includes(phase)&&!photo.active&&!u.air&&!u.swim66&&!u.rope66&&!u.wallState&&!u.climb&&!u.pick&&!u.bird71&&!u.geckoRide88&&!u.gecko88&&!u.mount88&&!u.job67?.lock&&!u.crawl169;}
 function dispose(){if(!state)return;const s=state;state=null;restoreHeadPose();s.g.parent?.remove(s.g);s.g.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});}
 function mesh(parent,geo,color){const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,roughness:.65}));m.userData.noInk=true;parent.add(m);return m;}
 function props(){const g=new THREE.Group(),cig=new THREE.Group(),lighter=new THREE.Group();g.name='Pip cigarette gesture';g.add(cig,lighter);root.add(g);const paper=mesh(cig,new THREE.CylinderGeometry(.003,.003,.031,8),0xe9dfc5);paper.rotation.x=Math.PI/2;paper.position.z=.024;const filter=mesh(cig,new THREE.CylinderGeometry(.0031,.0031,.011,8),0xae7947);filter.rotation.x=Math.PI/2;filter.position.z=.006;const ember=mesh(cig,new THREE.SphereGeometry(.0032,8,6),0xdd6826);ember.position.z=.041;ember.material.emissive.setHex(0xf65715);ember.material.emissiveIntensity=0;const ash=mesh(cig,new THREE.CylinderGeometry(.0032,.003,.004,8),0x857e73);ash.rotation.x=Math.PI/2;ash.position.z=.039;
 const metal=mesh(lighter,new THREE.BoxGeometry(.016,.021,.007),0xa7b7ad);metal.material.metalness=.8;metal.position.y=.006;const lid=new THREE.Group();lid.position.set(-.008,.016,0);lighter.add(lid);const cap=mesh(lid,new THREE.BoxGeometry(.016,.006,.007),0xb8c2bb);cap.position.set(.008,.003,0);const flame=mesh(lighter,new THREE.SphereGeometry(1,8,6),0xffcc70);flame.scale.set(.003,.008,.003);flame.position.y=.024;flame.material.emissive.setHex(0xff8f20);flame.material.emissiveIntensity=2;flame.visible=false;
 const smoke=[];for(let i=0;i<18;i++){const puff=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.MeshBasicMaterial({color:0xcfd5cb,transparent:true,opacity:0,depthWrite:false}));puff.userData.noInk=true;puff.visible=false;g.add(puff);smoke.push({m:puff,age:9,v:V()});}return {g,cig,lighter,ember,lid,flame,smoke};}
 function toggle(){if(state){if(!state.ending){state.ending=true;state.endTime=0;state.endFrom=state.cig.position.clone();sayToast('Pip puts it out.');}return;}if(!gameplayActive()||!eligible())return sayToast('Stand clear or sit in the car to light up.');if(car77?.riding&&Math.abs(car77.speed)>.25)return sayToast('Stop the car to use the lighter.');state={...props(),owner:root,actor:rat,phase,time:0,ending:false,endTime:0,lit:false,emit:0,seed:0,errors:{},wasDriving:!!car77?.riding};sayToast('Pip lights a cigarette. Use Pip’s actions or Car controls to put it out.');}
 function arm(g,side,target,weight){const u=g.userData,b=u.pipBones;g.updateWorldMatrix(true,true);const current=b[side+'Hand'].getWorldPosition(V());for(const part of ['Arm','ForeArm','Hand']){const name=side+part;if(u.pipRest[name])b[name].quaternion.copy(u.pipRest[name]);}g.updateWorldMatrix(true,true);state.errors[side]=solveArm203(THREE,g,side,current.lerp(target,weight));}
 function pose(g){const s=state;if(!s||s.actor!==g)return;if(!eligible()||s.owner!==root||s.phase!==phase){dispose();return;}restoreHeadPose();const b=g.userData.pipBones;const cycle=(Math.max(0,s.time-5.1))%7,puff=s.lit&&cycle<2.1,weight=s.time<2.4?ease((s.time-.65)/1.45):s.time<5.1?1:cycle<2.1?ease(cycle/.6)*ease((2.1-cycle)/.5):0;g.updateWorldMatrix(true,true);const q=new THREE.Quaternion().setFromAxisAngle(V(0,1,0),g.rotation.y),forward=V(0,0,1).applyQuaternion(q),right=V(1,0,0).applyQuaternion(q),up=V(0,1,0);if(b.Head){headPose={bone:b.Head,quaternion:b.Head.quaternion.clone()};const world=b.Head.getWorldQuaternion(new THREE.Quaternion()),delta=new THREE.Quaternion().setFromAxisAngle(right,(s.time<5.1?.5:.8)*weight*(s.ending?1-ease(s.endTime/.8):1));b.Head.quaternion.copy(b.Head.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(delta.multiply(world)));g.updateWorldMatrix(true,true);}const mouth=(b.headfront||b.Head).getWorldPosition(V()).addScaledVector(up,-.008).addScaledVector(forward,-.004),hips=b.Hips.getWorldPosition(V()),rest=hips.clone().addScaledVector(right,0).addScaledVector(up,.14).addScaledVector(forward,.035),car=car77?.riding?car77:null;
 // The first-person head is hidden only after this hook, preserving true muzzle coordinates.
 const grip=mouth.clone().addScaledVector(forward,-.014).addScaledVector(right,.009);
 let target=rest.clone().lerp(grip,s.time<5.1?0:weight),blend=ease(s.time/.6);const busy=car&&(car.reach||car.drifting);
 if(s.ending){const end=car?car.ashTarget.getWorldPosition(V()):rest.clone().addScaledVector(forward,.012);target.lerp(end,ease(s.endTime/.8));blend*=1-ease((s.endTime-1)/.5);s.flame.visible=false;}
 if(!busy)arm(g,'Left',target,blend);if(s.ending&&!car)arm(g,'Right',target.clone().addScaledVector(forward,.027),ease(s.endTime/.4)*(1-ease((s.endTime-1)/.5)));
 const lighting=s.time>2.1&&s.time<4.8&&!s.ending&&!s.lit;
 if(lighting){const flameTarget=rest.clone().addScaledVector(right,-.009).addScaledVector(forward,.055).addScaledVector(up,-.024);arm(g,'Right',flameTarget,ease((s.time-2.1)/.5)*ease((4.8-s.time)/.6));}
 g.updateWorldMatrix(true,true);const hand=b.LeftHand.getWorldPosition(V()),rhand=b.RightHand.getWorldPosition(V());s.cig.quaternion.copy(q);s.cig.position.copy(busy?mouth:hand.clone().addScaledVector(right,-.009).addScaledVector(forward,.014));s.cig.visible=s.time>.55&&(!s.ending||s.endTime<1.15);
 s.lighter.position.copy(rhand);s.lighter.quaternion.copy(q);s.lighter.visible=s.time>1.7&&s.time<5.1&&!s.ending;s.lid.rotation.z=-ease((s.time-2)/.3)*2; s.flame.visible=s.time>2.7&&s.time<4.15&&!s.ending;s.flame.scale.y=.008*(1+Math.sin(s.time*43)*.15);
 if(s.time>=4.15)s.lit=true;s.ember.material.emissiveIntensity=s.lit?(puff?2.6:.55):0;s.mouth=mouth;s.forward=forward;s.puff=puff;s.tip=s.cig.position.clone().addScaledVector(forward,.043);
 }
 function tick(dt){const s=state;if(!s)return;if(s.owner!==root||s.actor!==rat||s.phase!==phase||!eligible()){dispose();return;}if(!gameplayActive()||document.hidden){s.g.visible=false;return;}s.g.visible=true;dt=Math.min(.05,Math.max(0,dt));if(s.wasDriving!==!!car77?.riding){dispose();return;}if(!s.lit&&car77?.riding&&Math.abs(car77.speed)>.3){dispose();return;}
 s.time+=dt;if(s.ending){s.endTime+=dt;if(s.endTime>=1.5){dispose();return;}}if(s.time>65&&!s.ending){s.ending=true;s.endTime=0;}
 s.emit+=dt;const cycle=Math.max(0,s.time-5.1)%7,exhale=s.lit&&cycle>2.1&&cycle<3.4&&!s.ending;if(s.lit&&!s.ending&&s.tip&&s.emit>(exhale?.09:.3)){s.emit=0;const p=s.smoke.find(p=>p.age>1.7);if(p){p.age=0;p.m.visible=true;p.m.position.copy(exhale?s.mouth:s.tip);p.v.copy(s.forward).multiplyScalar(exhale?.09:.012);p.v.y=.045+(s.seed%3)*.006;s.seed++;}}
 for(const p of s.smoke){if(p.age>1.7)continue;p.age+=dt;p.m.position.addScaledVector(p.v,dt);const size=.004+p.age*.014;p.m.scale.set(size,size*.8,size);p.m.material.opacity=Math.max(0,.15*(1-p.age/1.7));p.m.visible=p.age<1.7;}
 }
 const make=makeRat;makeRat=function(){const g=make(),animate=g.animate;g.animate=function(...args){restoreHeadPose();animate(...args);if(window.motoring206)window.motoring206.restPose(g);if(!g.userData.drive77)pose(g);};return g;};
 const previous=tickWorld38;tickWorld38=function(dt){previous(dt);tick(dt);};
 const clearBefore=clear;clear=function(...args){dispose();return clearBefore(...args);};
 window.pipSmoke205={toggle,pose,tick,dispose,get state(){return state;}};
})();
