/* Walking first person, persistent quick whistle and calibrated motoring instruments. */
(()=>{
 const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),clamp=THREE.MathUtils.clamp;
 cockpit207.set('size','small');for(const id of ['start','newgame'])$(id).addEventListener('click',()=>cockpit207.set('size','small'));
 const whistle=document.createElement('button');whistle.id='quickLizard209';whistle.textContent='🦎';whistle.title='Whistle for your lizard';whistle.setAttribute('aria-label','Whistle for your lizard');whistle.onclick=()=>$('geckoWhistle193').click();document.body.appendChild(whistle);
 const view=document.createElement('button');view.id='footView209';view.textContent='1P';view.title='First-person view';view.setAttribute('aria-label','Switch to first-person walking view');document.body.appendChild(view);
 const speed=document.createElement('output');speed.id='speed209';speed.setAttribute('aria-label','Vehicle speed and gear');document.body.appendChild(speed);
 const style=document.createElement('style');style.textContent=`#quickLizard209,#footView209{position:fixed;z-index:48;width:44px;height:44px;min-height:44px;padding:0;border:1px solid #d4d9ba44;border-radius:50%;background:#20372dbb;color:#f2e6c9;font:600 12px system-ui;touch-action:manipulation}#quickLizard209{right:62px;top:148px}body.driving203 #quickLizard209{top:68px}#footView209{left:14px;bottom:236px}#footView209[aria-pressed=true]{background:#c4a875;color:#213b30}#quickLizard209[hidden],#footView209[hidden],#speed209[hidden]{display:none!important}body #navigation201 #geckoWhistle193{display:none!important}#speed209{position:fixed;right:94px;bottom:22px;color:#fff0d2;background:#20372dbb;border-radius:9px;padding:6px 9px;font:600 12px/1.3 system-ui;z-index:48;pointer-events:none;font-variant-numeric:tabular-nums}@media(max-height:520px){#quickLizard209{top:64px}#footView209{bottom:132px}#speed209{right:172px;bottom:14px}}`;document.head.appendChild(style);

 const point209=(x,z)=>({x:6+(x+86)/180*88,y:94-(z+25)/108*88});
 window.mapWide209=()=>phase==='scavenge'&&rat&&(rat.position.x<-21||rat.position.x>31||rat.position.z>40||rat.position.z<-14);
 function citySVG(){return city204.roads209.map(([a,b,c,d])=>{const p=point209(a,d),q=point209(b,c);return `<rect x="${p.x}" y="${p.y}" width="${q.x-p.x}" height="${q.y-p.y}" fill="#9da79d"/>`;}).join('')+'<text x="50" y="5" text-anchor="middle" fill="#fff2d3" font-size="4">NEIGHBOURHOOD ROADS</text>';}
 const oldMap=openYard201;openYard201=function(selected){if(selected!=='city')return oldMap(selected);const p=point209(rat.position.x,rat.position.z);modal('City roads',`<div class="map201"><svg viewBox="0 0 100 100" preserveAspectRatio="none">${citySVG()}<circle cx="${p.x}" cy="${p.y}" r="1.5" fill="#ffe2a0" stroke="#20372d" stroke-width=".5"/></svg></div><p>Gold dot: Pip. The north driveway connects to the city. East, west and southern roads form a complete driving circuit.</p>`,[['Yard destinations',()=>oldMap('home')],['Objectives',openObjectives200],['Close',closeModal]]);};
 let localTerrain=null,terrainWide=null;
 let first=false,saved=null,suspended=false;
 function toggleFoot(force){const next=typeof force==='boolean'?force:!first;if(next===first)return;if(next){if(car77?.riding||!gameplayActive())return;saved={near:camera.near,fov:camera.fov,pitch:gameCam.pitch,yaw:gameCam.yaw};gameCam.yaw=rat.rotation.y+Math.PI;gameCam.pitch=.58;camera.near=.015;camera.fov=85;first=true;}else{first=false;suspended=false;if(saved){camera.near=saved.near;camera.fov=saved.fov;gameCam.pitch=saved.pitch;gameCam.yaw=saved.yaw;saved=null;}gameCam.ready=false;}camera.updateProjectionMatrix();view.textContent=first?'3P':'1P';view.setAttribute('aria-pressed',String(first));view.setAttribute('aria-label',first?'Switch to third-person walking view':'Switch to first-person walking view');}
 view.onclick=()=>toggleFoot();addEventListener('keydown',e=>{if(e.code==='KeyV'&&!e.repeat&&!car77?.riding&&!/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||''))toggleFoot();});
 const enter=enterCar77;enterCar77=function(){toggleFoot(false);return enter();};const clearBefore=clear;clear=function(){toggleFoot(false);return clearBefore();};
 const cam=tickGameplayCamera;tickGameplayCamera=function(dt){if(!first){cam(dt);return;}if(car77?.riding||!['scavenge','explore','house','inside'].includes(phase)){toggleFoot(false);cam(dt);return;}if(photo.active||!gameplayActive()){if(!suspended){camera.near=saved.near;camera.fov=saved.fov;camera.updateProjectionMatrix();suspended=true;}cam(dt);return;}if(suspended){camera.near=.015;camera.fov=85;camera.updateProjectionMatrix();suspended=false;}
  // Fixed eye height avoids transmitting the walking skeleton's head bob to the camera.
  const height=rat.userData.crawl169?.19:rat.userData.swim66?.25:.40;
  camera.position.copy(rat.position).add(V(0,height,0));const pitch=clamp(gameCam.pitch-.58,-.8,.8);const direction=V(-Math.sin(gameCam.yaw)*Math.cos(pitch),-Math.sin(pitch),-Math.cos(gameCam.yaw)*Math.cos(pitch));camera.lookAt(camera.position.clone().add(direction));$('cameraTools').style.display='none';};
 const render=renderer.render;renderer.render=function(s,c){if(first&&!suspended&&!photo.active&&gameplayActive()&&s===scene&&c===camera&&rat){const visible=rat.visible;rat.visible=false;try{return render.call(renderer,s,c);}finally{rat.visible=visible;}}return render.call(renderer,s,c);};
 function telemetry(c){const kph=Math.abs(c.speed)*3.6;const gear=c.speed<-.08?'R':kph<.3?'N':kph<10?'1':kph<21?'2':'3';const ratio=gear==='1'?410:gear==='2'?230:155;const rpm=c.ignition206?Math.min(6000,850+kph*ratio):0;return {kph,gear,rpm};}
 function dial(c,index,max,label){const pivot=c.gauges206[index];if(!pivot)return;const r=index===0?.038:.025;const cv=document.createElement('canvas');cv.width=cv.height=256;const x=cv.getContext('2d');x.fillStyle='#17241f';x.fillRect(0,0,256,256);x.strokeStyle='#e3d4a7';x.fillStyle='#e3d4a7';x.textAlign='center';x.textBaseline='middle';x.font='bold 22px sans-serif';for(let i=0;i<=8;i++){const a=-2.3+i/8*4.6,s=Math.sin(a),co=Math.cos(a);x.beginPath();x.moveTo(128+s*103,128-co*103);x.lineTo(128+s*91,128-co*91);x.lineWidth=3;x.stroke();if(i%2===0)x.fillText(String(Math.round(max*i/8)),128+s*72,128-co*72);}x.font='18px sans-serif';x.fillText(label,128,174);const tex=new THREE.CanvasTexture(cv);tex.encoding=THREE.sRGBEncoding;const face=new THREE.Mesh(new THREE.CircleGeometry(r,32),new THREE.MeshBasicMaterial({map:tex}));face.position.copy(pivot.position);face.position.z+=.004;face.rotation.y=Math.PI;face.name='Calibrated '+label+' dial';c.visual.add(face);pivot.rotation.z=-2.3;}
 let gaugeCar=null;
 const tick=tickWorld38;tickWorld38=function(dt){tick(dt);const terrain=document.querySelector('#miniMap171 .mapTerrain207'),wide=!!window.mapWide209();if(terrain&&wide!==terrainWide){localTerrain??=terrain.innerHTML;terrain.innerHTML=wide?citySVG():localTerrain;terrainWide=wide;}const playing=!!rat&&!photo.active&&gameplayActive();whistle.hidden=!playing;view.hidden=!playing||!!car77?.riding;const c=car77;speed.hidden=!playing||!c?.riding;if(c?.gauges206&&gaugeCar!==c){gaugeCar=c;dial(c,0,40,'km/h');dial(c,1,6,'RPM ×1000');}if(c?.gauges206){const v=telemetry(c);c.gauges206[0].rotation.z=-2.3+clamp(v.kph/40,0,1)*4.6;c.gauges206[1].rotation.z=-2.3+clamp(v.rpm/6000,0,1)*4.6;const label=Math.round(v.kph)+' km/h · '+v.gear;if(speed.textContent!==label)speed.textContent=label;}}
 window.touring209={telemetry,toggleFoot,get firstPerson(){return first;}};
})();
