/* Hinged cabin, adjustable mirror views and persistent roadside maintenance. */
(()=>{
 const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),clamp=THREE.MathUtils.clamp;
 const defaults=()=>({oil:100,coolant:100,condition:100,temperature:22,roof:false,windows:false,upgrades:{},mirrors:[{yaw:0,pitch:0},{yaw:0,pitch:0},{yaw:0,pitch:0}],finds:{}});
 function data(){home.vehicle219??=defaults();const s=home.vehicle219;for(const [k,v]of Object.entries(defaults()))if(s[k]===undefined)s[k]=v;return s;}
 const specs={oil219:['Engine oil',0xb28a42],coolant219:['Cooling water',0x62a6b5],spark219:['Spark plugs',0xc9c5b6],belt219:['Drive belt',0x363c33],radiator219:['Radiator core',0x869b8c],tyres219:['Road tyres',0x313930]};
 function box(parent,w,h,d,x,y,z,color,name){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.65}));m.position.set(x,y,z);m.name=name;m.castShadow=true;m.userData.noInk=true;parent.add(m);return m;}
 for(const [id,[name,color]]of Object.entries(specs))ITEMS[id]={name,r:.22,build(){const g=new THREE.Group();box(g,.25,.35,.17,0,.18,0,color,name);box(g,.08,.05,.07,0,.38,0,0xd8c9a5,'Cap');return g;}};
 const upgrades={engine:{label:'Ignition & belt',needs:{spark219:1,belt219:1},effect:'15% more engine power, higher speed limit'},cooling:{label:'Larger radiator',needs:{radiator219:1},effect:'Slower heat build-up'},tyres:{label:'Road tyres',needs:{tyres219:1},effect:'20% more cornering grip'},brakes:{label:'Rebuilt brakes',needs:{foil:3,nail:2},effect:'20% stronger braking'}};
 let panel,carSeen=null,caches=[],cacheRoot=null,service=null,persist=0;
 const near=()=>car77&&phase==='scavenge'&&(car77.riding||rat.position.distanceTo(car77.g.position)<2.4);
 function hinge(parent,objects,point,name){const p=new THREE.Group();p.name=name;p.position.copy(point);parent.add(p);parent.updateWorldMatrix(true,true);for(const o of objects)p.attach(o);return p;}
 function attach(c){if(c.cabin219)return;const b=c.visual,state=data();b.updateWorldMatrix(true,true);
  const hood=hinge(b,[b.getObjectByName('Sculpted bonnet')],V(0,.52,.15),'Hood hinge');
  const doors=[];for(const side of [-1,1]){const objects=b.children.filter(o=>o.name==='Hinged door skin'&&o.userData.doorSide219===side||['Door seam','Door handle','Saddle leather door insert','Walnut door cap','Door inlay','Door stitching','Cockpit chrome rim'].includes(o.name)&&(o.position.x?Math.sign(o.position.x)===side:Math.sign(o.geometry?.attributes.position?.getX(0)||0)===side));const pivot=hinge(b,objects,V(side*.63,.30,.15),side<0?'Driver door hinge':'Passenger door hinge');const glass=new THREE.Mesh(new THREE.PlaneGeometry(.55,.32),new THREE.MeshStandardMaterial({color:0xa3c2bb,transparent:true,opacity:.25,roughness:.12,side:THREE.DoubleSide,depthWrite:false}));glass.rotation.y=Math.PI/2;glass.position.set(-side*.02,.39,-.4);glass.name='Sliding side window';pivot.add(glass);doors.push({pivot,glass,open:false,value:0});}
  const roof=new THREE.Group();roof.position.set(0,.61,-.73);roof.name='Folding convertible roof';b.add(roof);const back=box(roof,1.03,.035,.69,0,.36,.20,0x443a2d,'Canvas rear roof');const front=new THREE.Group();front.position.set(0,.36,.545);roof.add(front);box(front,1.02,.035,.34,0,0,.17,0x443a2d,'Canvas front roof');for(const x of [-.49,.49])box(roof,.026,.38,.026,x,.18,-.09,0x7f8675,'Roof support');
  const engine=new THREE.Group();engine.name='Serviceable engine';b.add(engine);box(engine,.49,.20,.48,0,.36,.58,0x3e4844,'Engine block');for(const x of [-.17,0,.17])box(engine,.04,.035,.36,x,.475,.58,0x9d9a7e,'Valve cover rib');box(engine,.62,.22,.04,0,.37,.93,0x798773,'Radiator');box(engine,.14,.14,.18,.35,.36,.54,0xc3d6bb,'Coolant reservoir');const oil=box(engine,.055,.025,.055,-.17,.49,.64,0xd1a94e,'Oil filler');const coolant=box(engine,.055,.025,.055,.35,.445,.54,0x598fc0,'Coolant cap');
  const mirrors=c.mirrors206.map((m,i)=>{const pivot=hinge(c.g,[m.face,m.frame],V(m.x,m.y,m.z),'Adjustable mirror '+i);m.pivot219=pivot;m.yaw219=state.mirrors[i].yaw;m.pitch219=state.mirrors[i].pitch;return m;});
  c.cabin219={hood,hoodOpen:false,hoodValue:0,doors,roof,front,roofValue:state.roof?1:0,windowValue:state.windows?1:0,engine,oil,coolant,mirrors};
 }
 function stopped(){if(!near())return false;if(Math.abs(car77.speed)>.08){sayToast('Park before using this control.');return false;}return true;}
 function interlocked(){const a=car77?.cabin219;return !!a&&(a.hoodOpen||a.hoodValue>.02||a.doors.some(d=>d.open||d.value>.02)||Math.abs(a.roofValue-(data().roof?1:0))>.01);}
 function toggle(kind,index=0){if(!stopped())return false;attach(car77);const a=car77.cabin219;
  if(kind==='hood'){if(car77.ignition206)return sayToast('Stop the engine before opening the hood.');a.hoodOpen=!a.hoodOpen;}
  else if(kind==='door')a.doors[index].open=!a.doors[index].open;
  else if(kind==='roof')data().roof=!data().roof;
  else if(kind==='windows')data().windows=!data().windows;
  save();window.tutorial219?.record(kind);refresh();return true;
 }
 function adjustMirror(index,yaw,pitch){if(!stopped()||!car77.riding)return false;const m=car77.cabin219.mirrors[index],s=data().mirrors[index];s.yaw=clamp(yaw,-.6,.6);s.pitch=clamp(pitch,-.4,.4);m.yaw219=s.yaw;m.pitch219=s.pitch;car77.reach={kind:'mirror',target:m.face,side:index===1?'Right':'Left',time:car77.reach?.target===m.face?Math.min(.8,car77.reach.time):0,duration:1.7};roadsterControls203.setView(1);save();window.tutorial219?.record('mirrors');return true;}
 function tuning(){const s=data();return {power:(s.upgrades.engine?1.15:1)*(.45+.55*s.condition/100)*(s.temperature>105?.5:1)*(s.oil<10?.45:1),topSpeed:s.upgrades.engine?1.1:1,brakes:s.upgrades.brakes?1.2:1,grip:s.upgrades.tyres?1.2:1};}
 function serviceStart(kind){if(!stopped())return false;const c=car77,a=c.cabin219,s=data();if(c.riding)return sayToast('Step out and stand at the front of the car.');if(c.ignition206)return sayToast('Switch the engine off first.');if(!a.hoodOpen||a.hoodValue<.95)return sayToast('Open the hood and let it lift first.');if(service)return false;
  const target=(kind==='coolant'?a.coolant:a.oil);if(rat.position.distanceTo(target.getWorldPosition(V()))>.85)return sayToast('Walk closer to the open engine at the front.');if(kind==='coolant'&&s.temperature>60)return sayToast('Let the engine cool below 60°C before opening the water cap.');
  const needs=kind==='oil'?{oil219:1}:kind==='coolant'?{coolant219:1}:kind==='repair'?{foil:2,nail:1}:upgrades[kind]?.needs;
  if(!needs)return false;if(upgrades[kind]&&s.upgrades[kind])return false;if((kind==='oil'||kind==='coolant')&&s[kind]>=99)return sayToast('Already full.');if(kind==='repair'&&s.condition>=99)return sayToast('Engine is already healthy.');
  if(!Object.entries(needs).every(([id,n])=>(inv[id]||0)>=n))return sayToast('Missing supplies. Check the roadside parts crates.');
  const prop=new THREE.Group();box(prop,.06,.1,.04,0,0,0,kind==='coolant'?0x62a6b5:0xb28a42,'Service bottle');const stream=box(prop,.008,.13,.008,0,-.10,0,kind==='coolant'?0x9fcbd0:0x8e6d39,'Pouring stream');stream.visible=kind==='oil'||kind==='coolant';root.add(prop);
  service={kind,target,needs,time:0,prop,owner:root,car:c};panel.hidden=true;keys={};joy.x=joy.z=0;sayToast('Pip is '+(kind==='oil'||kind==='coolant'?'topping up '+kind:'working on the engine')+'…');return true;
 }
 function finishService(){const job=service,s=data();if(Object.entries(job.needs).every(([k,n])=>(inv[k]||0)>=n)){for(const [k,n]of Object.entries(job.needs))inv[k]-=n;if(job.kind==='oil'||job.kind==='coolant')s[job.kind]=100;else if(job.kind==='repair')s.condition=Math.min(100,s.condition+45);else s.upgrades[job.kind]=true;save();bag();window.tutorial219?.record('service');sayToast('Finished — '+(upgrades[job.kind]?.label||job.kind));}cancelService();}
 function cancelService(){if(service){service.prop.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});service.prop.parent?.remove(service.prop);service=null;}}
 const make=makeRat;makeRat=function(){const g=make(),animate=g.animate;g.animate=function(...args){animate(...args);if(service&&g===rat&&g.userData.pipBones){const b=g.userData.pipBones;g.rotation.y=Math.atan2(service.target.getWorldPosition(V()).x-g.position.x,service.target.getWorldPosition(V()).z-g.position.z);const q=Math.min(1,service.time/.7,(3.5-service.time)/.7),hand=b.LeftHand;const rest=hand.getWorldPosition(V()),target=service.target.getWorldPosition(V()).add(V(0,.09,0));solveArm203(THREE,g,'Left',rest.lerp(target,clamp(q,0,1)));service.prop.position.copy(hand.getWorldPosition(V()));service.prop.rotation.z=-.65;}};return g;};
 function refresh(){if(!panel||panel.hidden||!near())return;const a=car77.cabin219,s=data(),pct=n=>Math.round(n)+'%';panel.innerHTML='<strong>Roadster workshop</strong><button data-v219="close" aria-label="Close workshop">×</button><p>Park to adjust the cabin. For service: engine off, step out, open hood, approach the front.</p><div id="controls219"></div><p id="engineStatus219">Oil '+pct(s.oil)+' · Water '+pct(s.coolant)+'<br>Engine '+pct(s.condition)+' · '+Math.round(s.temperature)+'°C</p><div id="service219"></div><p>Parts crates: beside the car’s original parking spot and on the city approach (z40 and z54). Contents are saved in your bag.</p>';
  const add=(host,label,fn,disabled=false)=>{const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=fn;host.appendChild(b);return b;};panel.querySelector('[data-v219=close]').onclick=()=>panel.hidden=true;const controls=$('controls219');add(controls,a.hoodOpen?'Close hood':'Open hood',()=>toggle('hood'));for(const [i,d]of a.doors.entries())add(controls,(d.open?'Close ':'Open ')+(i?'passenger':'driver')+' door',()=>toggle('door',i));add(controls,s.roof?'Fold roof open':'Close convertible roof',()=>toggle('roof'));add(controls,s.windows?'Lower windows':'Raise windows',()=>toggle('windows'));
  for(let i=0;i<3;i++)add(controls,'Adjust '+['centre','left','right'][i]+' mirror',()=>mirrorPanel(i),!car77.riding);
  const repairs=$('service219');for(const [k,label]of [['oil','Add engine oil'],['coolant','Add cooling water'],['repair','Repair engine']])add(repairs,label+(k==='repair'?' · 2 foil + 1 nail':' · '+(inv[k==='oil'?'oil219':'coolant219']||0)+' bottles'),()=>serviceStart(k));for(const [k,u]of Object.entries(upgrades))add(repairs,(s.upgrades[k]?'Installed: ':'Fit: ')+u.label+' — '+u.effect+' ('+Object.entries(u.needs).map(([id,n])=>n+' '+ITEMS[id].name).join(', ')+')',()=>serviceStart(k),!!s.upgrades[k]);
 }
 function mirrorPanel(i){if(!stopped())return;const s=data().mirrors[i];panel.innerHTML='<strong>'+['Centre','Left','Right'][i]+' mirror</strong><p>Adjust while parked. Pip reaches over as the mirror and its view turn.</p><label>Left / right<input id="mirrorYaw219" type="range" min="-0.6" max="0.6" step="0.02" value="'+s.yaw+'"></label><label>Up / down<input id="mirrorPitch219" type="range" min="-0.4" max="0.4" step="0.02" value="'+s.pitch+'"></label><button id="mirrorBack219">Done</button>';
  for(const id of ['mirrorYaw219','mirrorPitch219'])$(id).oninput=()=>adjustMirror(i,Number($('mirrorYaw219').value),Number($('mirrorPitch219').value));$('mirrorBack219').onclick=refresh;
 }
 function open(){if(!near())return sayToast('Stand beside the roadster to open its workshop.');attach(car77);cockpit205.toggle(false);closeModal();panel.hidden=false;refresh();if(!car77.riding&&!home.tutorial219?.started.service)window.tutorial219?.start('service');}
 panel=document.createElement('section');panel.id='workshop219';panel.hidden=true;panel.setAttribute('aria-label','Roadster workshop');document.body.appendChild(panel);panel.addEventListener('pointerdown',e=>e.stopPropagation());
 const style=document.createElement('style');style.textContent='#workshop219{position:fixed;z-index:38;right:12px;top:max(100px,20vh);width:min(320px,calc(100vw - 36px));max-height:48dvh;overflow:auto;padding:14px;box-sizing:border-box;background:#19382ff5;color:#efe0bf;border:1px solid #bba274;border-radius:16px;font:13px/1.45 system-ui;box-shadow:0 8px 30px #0005}#workshop219[hidden]{display:none}#workshop219 button{min-height:44px;padding:10px;margin:3px;border:1px solid #bcaa7c55;border-radius:9px;background:#e7d4a7;color:#20392e;font:600 12px system-ui}#workshop219 button:disabled{opacity:.5}#workshop219 input{display:block;width:100%;min-height:44px}#workshop219 label{display:block;margin:12px 0}#workshop219 [data-v219=close]{float:right}#workshop219 p{margin:10px 0}';document.head.appendChild(style);
 const workshopButton=document.createElement('button');workshopButton.className='cockpit205-secondary';workshopButton.textContent='Roof · doors · mirrors · engine';workshopButton.onclick=open;cockpit206.groups.Cabin.push(workshopButton);cockpit205.drawer.querySelector('.cockpit205-grid').appendChild(workshopButton);workshopButton.hidden=true;
 const actions=motoring206.actions;motoring206.actions=function(){actions();const b=document.createElement('button');b.className='btn';b.textContent='Car workshop';b.onclick=open;$('modalActions').appendChild(b);};$('pipActions205').onclick=motoring206.actions;
 const enter=enterCar77;enterCar77=function(){if(service)return;const result=enter();if(car77?.riding){attach(car77);const d=car77.cabin219.doors[0];d.value=1;d.open=false;window.tutorial219?.record('enterCar');}return result;};
 const exit=exitCar77;exitCar77=function(){const c=car77;if(c?.riding&&Math.abs(c.speed)>.15)return sayToast('Stop before stepping out.');const result=exit();if(c&&!c.riding&&c.cabin219){c.cabin219.doors[0].open=true;panel.hidden=true;window.tutorial219?.record('exitCar');}return result;};
 const ignition=motoring206.ignition;motoring206.ignition=function(){if(!car77?.ignition206&&(data().condition<5||data().oil<1))return sayToast('Service the engine before starting.');ignition();if(car77?.ignition206)window.tutorial219?.record('ignition');};$('ignition211').onclick=motoring206.ignition;
 // Existing secondary ignition button captured the old function.
 for(const b of cockpit206.groups.Drive)if(b.textContent==='Start engine')b.onclick=motoring206.ignition;
 const driveBefore=controlCar77;controlCar77=function(dt,options){if(service)return 0;const c=car77,old=c?.speed||0,result=driveBefore(dt,options);if(c?.riding&&old>2&&c.speed===0&&gameplayActive()&&!interlocked()){data().condition=Math.max(0,data().condition-Math.min(8,old));save();}return result;};
 const footControl=window.control;control=function(dt,options){if(service)return 0;return footControl(dt,options);};
 function seed(){if(phase!=='scavenge'||cacheRoot===root)return;cacheRoot=root;caches=[];for(const [id,x,z,items]of [['yard',7.7,18,{oil219:2,coolant219:2,spark219:1,belt219:1}],['approach',4.9,40,{oil219:3,coolant219:3,radiator219:1}],['city',4.9,54,{oil219:3,coolant219:3,tyres219:1}]]){const g=new THREE.Group();g.position.set(x,0,z);box(g,.42,.24,.3,0,.12,0,0x765033,'Roadside parts crate');box(g,.29,.03,.2,0,.26,0,0xd4ba78,'Parts crate lid');root.add(g);caches.push({id,g,items});}}
 const grab=window.grab;window.grab=function(){if(service)return;if(!car77?.riding&&phase==='scavenge'){const cache=caches.find(c=>rat.position.distanceTo(c.g.position)<.9);if(cache){const found=data().finds[cache.id]??={};let added=0;for(const [id,n]of Object.entries(cache.items)){const take=Math.min(n-(found[id]||0),Math.max(0,bagCapacity()-totalBag()));if(take){inv[id]=(inv[id]||0)+take;found[id]=(found[id]||0)+take;added+=take;}}save();bag();sayToast(added?'Collected '+added+' service supplies.':totalBag()>=bagCapacity()?'Bag full — make room for parts.':'This parts crate is empty.');return;}}return grab();};
 const tick=tickWorld38;tickWorld38=function(dt){tick(dt);seed();if(!car77||car77.owner!==root){panel.hidden=true;cancelService();return;}attach(car77);const c=car77,a=c.cabin219,s=data();if(!near()||!gameplayActive())panel.hidden=true;if(!gameplayActive()||document.hidden)return;dt=Math.min(.05,Math.max(0,dt));const move=(v,t,speed)=>v+clamp(t-v,-dt*speed,dt*speed),ease=t=>t*t*(3-2*t);
  a.hoodValue=move(a.hoodValue,a.hoodOpen?1:0,.65);a.hood.rotation.x=-ease(a.hoodValue)*1.25;
  for(const [i,d]of a.doors.entries()){d.value=move(d.value,d.open?1:0,1.05);d.pivot.rotation.y=(i?-1:1)*ease(d.value)*1.1;}
  a.roofValue=move(a.roofValue,s.roof?1:0,.28);const roof=ease(a.roofValue);a.roof.rotation.x=-(1-roof)*1.6;a.front.rotation.x=(1-roof)*2.7;a.roof.position.y=.61-(1-roof)*.03;
  a.windowValue=move(a.windowValue,s.windows?1:0,.55);for(const d of a.doors){d.glass.position.y=.10+.29*ease(a.windowValue);d.glass.scale.y=Math.max(.001,ease(a.windowValue));d.glass.visible=a.windowValue>.005;}
  for(const m of a.mirrors){m.pivot219.rotation.y=THREE.MathUtils.damp(m.pivot219.rotation.y,m.yaw219,6,dt);m.pivot219.rotation.x=THREE.MathUtils.damp(m.pivot219.rotation.x,m.pitch219,6,dt);}
  if(c.ignition206){s.oil=Math.max(0,s.oil-dt*(.008+Math.abs(c.speed)*.001));s.coolant=Math.max(0,s.coolant-dt*(.005+(s.temperature>100?.04:0)));const target=78+(s.coolant<20?65:0)+(s.oil<15?30:0);s.temperature+= (target-s.temperature)*dt*(s.upgrades.cooling?.018:.03);if(s.temperature>110||s.oil<5)s.condition=Math.max(0,s.condition-dt*.12);if(s.condition<5||s.oil<1){c.ignition206=false;stopEngine77();sayToast('Engine stopped — check oil and condition.');}}
  else s.temperature=Math.max(22,s.temperature-dt*.8);
  if(service){if(service.owner!==root||service.car!==c||!a.hoodOpen||c.riding)cancelService();else{service.time+=dt;if(service.time>=3.5)finishService();}}
  if(!panel.hidden&&$('engineStatus219'))$('engineStatus219').textContent='Oil '+Math.round(s.oil)+'% · Water '+Math.round(s.coolant)+'% · Engine '+Math.round(s.condition)+'% · '+Math.round(s.temperature)+'°C';
  if(!c.riding&&caches.some(k=>rat.position.distanceTo(k.g.position)<.9)){ui.prompt.style.display='block';ui.prompt.textContent='Roadside parts crate · Grab supplies';$('padE').textContent='Collect parts';}
  persist+=dt;if(persist>10){persist=0;save();}
 };
 window.vehicle219={data,attach,toggle,adjustMirror,interlocked,tuning,serviceStart,open,refresh,cancelService,get service(){return service;},get caches(){return caches;},upgrades};
})();
