// Real Chromium/WebGL UI regression; run with WW_PLAYWRIGHT and WW_CHROMIUM paths.
const {chromium}=require(process.env.WW_PLAYWRIGHT || 'playwright');
(async()=>{const fs=require('fs'),path=require('path');const server=require('http').createServer((req,res)=>{const p=path.join(path.resolve(__dirname,'..'),decodeURIComponent(req.url.split('?')[0])==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8877,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.WW_CHROMIUM || '/tmp/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:412,height:820},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8877',{waitUntil:'domcontentloaded'});await page.waitForTimeout(5000);await page.evaluate(async()=>{await loadApprovedPip();$('title').style.display='none';$('openingVideo51').style.display='none';voiceOn=false;home.tutorial219={done:{foot:true,car:true,sewer:true},step:{},started:{},carRevision:231};startHouse();});
await page.waitForTimeout(1200);await page.screenshot({path:'/tmp/ww-home231.png'});
await page.evaluate(()=>openCraftBook());await page.waitForTimeout(500);await page.screenshot({path:'/tmp/ww-craft231.png'});
const stray=await page.locator('button:visible').evaluateAll(bs=>bs.filter(b=>!b.closest('#modal')).map(b=>b.id));if(stray.length)throw Error('Controls overlap Craft: '+stray.join(','));
await page.evaluate(()=>{closeModal();startScavenge();});await page.waitForTimeout(2000);
await page.evaluate(()=>{rat.position.copy(car77.g.position).add(new THREE.Vector3(1,0,0));rat.userData.job67=null;enterCar77();});await page.waitForTimeout(5000);await page.evaluate(()=>{for(let i=0;i<85;i++){tickWorld38(.05);rat.animate(.05,0);}tutorial219.pause();roadsterControls203.setView(2);});await page.screenshot({path:'/tmp/ww-car231.png'});
const carBounds=await page.evaluate(()=>Array.from(document.querySelectorAll('#cockpit205 button')).filter(b=>b.offsetWidth).map(b=>({text:b.textContent,x:b.getBoundingClientRect().x,y:b.getBoundingClientRect().y,w:b.offsetWidth,h:b.offsetHeight})));if(carBounds.some(b=>b.x<0||b.x+b.w>412||b.y+b.h>820))throw Error('Car controls off screen');if(carBounds.some(b=>b.text==='Outside view'))throw Error('Duplicate view button');
await page.evaluate(()=>{car77.speed=0;exitCar77();workshop231.start(true);});await page.waitForTimeout(300);await page.screenshot({path:'/tmp/ww-tools231.png'});
await page.evaluate(()=>{inv={};rat.position.set(7.2,0,21.8);tickWorld38(.2);});await page.locator('#supply231').click();await page.waitForTimeout(300);await page.getByRole('button',{name:'Done ✓ · Next',exact:true}).click();await page.getByRole('button',{name:'Open recipe',exact:true}).click();await page.getByRole('button',{name:'Make 1',exact:true}).click();if(!await page.evaluate(()=>!!home.tools.axe230))throw Error('Axe Make button did not craft');await page.screenshot({path:'/tmp/ww-axe231.png'});
await page.evaluate(()=>{closeModal();workshop231.pause();});await page.setViewportSize({width:360,height:740});await page.evaluate(()=>{car77.riding=true;roadsterControls203.setView(2);tickWorld38(.2);});await page.waitForTimeout(300);const small=await page.locator('#cockpit205').boundingBox();if(small.x<0||small.x+small.width>360||small.y+small.height>740)throw Error('Small-screen HUD overflow');await page.screenshot({path:'/tmp/ww-smallcar231.png'});

if(errors.length)throw Error('Browser errors: '+errors.join('; '));console.log(JSON.stringify({phoneViewports:[412,360],menuIsolation:true,compactCarControls:true,axeCraftedThroughUI:true,pageErrors:errors.length}));await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
