// CPU scene/logic integration check using the shipped Three.js and GLTFLoader.
// This is not a WebGL or browser visual test.
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert'),P=path.resolve(__dirname,'..');const THREE=require('../three-r128-build55.js');
const timers=[];const {element,document}=require('../tests/dom211.cjs');
const fakeRenderer={getRenderTarget:()=>null,setRenderTarget(){},shadowMap:{},capabilities:{isWebGL2:false,getMaxAnisotropy:()=>1},info:{render:{calls:0,triangles:0}},setPixelRatio(){},setSize(){},setClearColor(){},getPixelRatio:()=>1,render(){},dispose(){},domElement:element()};
const ctx={THREE,console,document,Blob,URL,TextDecoder,TextEncoder,ArrayBuffer,Uint8Array,Uint16Array,Uint32Array,Float32Array,performance,Math,Date,Map,Set,Promise,queueMicrotask,setTimeout:(f,ms)=>{if(ms<1000)return setTimeout(f,ms);timers.push(f);return 1},clearTimeout(){},setInterval(){},clearInterval(){},requestAnimationFrame(){},cancelAnimationFrame(){},addEventListener(){},removeEventListener(){},innerWidth:900,innerHeight:800,devicePixelRatio:1,matchMedia:()=>({matches:false,addEventListener(){}}),navigator:{userAgent:'scene-test',hardwareConcurrency:8},location:{search:'',href:'http://localhost',reload(){}},localStorage:{getItem:()=>null,setItem(){}},Image:function(){return element()},Audio:function(){return element()},fetch:async url=>{const file=path.join(P,String(url).split('?')[0]);return {ok:fs.existsSync(file),arrayBuffer:async()=>{const b=fs.readFileSync(file);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)},json:async()=>JSON.parse(fs.readFileSync(file,'utf8'))}},atob:s=>Buffer.from(s,'base64').toString('binary'),btoa:s=>Buffer.from(s,'binary').toString('base64'),__renderer:fakeRenderer};global.document=document;global.self=global;ctx.URLSearchParams=URLSearchParams;ctx.window=ctx;ctx.self=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(P,'GLTFLoader.js'),'utf8'),ctx);THREE.GLTFLoader.prototype.load=function(url,onLoad,onProgress,onError){try{const b=fs.readFileSync(path.join(P,url.split('?')[0]));this.parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'',onLoad,onError)}catch(e){onError?.(e)}};

document.body.innerHTML=fs.readFileSync(path.join(P,'canoe-preview.html'),'utf8');
vm.runInContext(fs.readFileSync(path.join(P,'canoe212.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(P,'canoe-preview213.js'),'utf8').replace('new THREE.WebGLRenderer({antialias:true})','__renderer'),ctx);
setTimeout(()=>{try{vm.runInContext(`if(!pip)throw Error('Pip missing');let max=0;for(let i=0;i<180;i++){animateRow(1/60);max=Math.max(max,...Object.values(gripErrors));}console.log(Object.fromEntries(['LeftArm','LeftForeArm','LeftHand','RightArm','RightForeArm','RightHand','Head'].map(n=>[n,bones[n].getWorldPosition(v()).toArray()])));console.log({maxGripError:max,effects:effects.length,hip:bones.Hips.getWorldPosition(v()).toArray()});if(max>.05)throw Error('Paddle unreachable');`,ctx);process.exit(0);}catch(e){console.error(e);process.exit(1);}},1500);
