// Minimal DOM for CPU game integration: no browser or pixel rendering is simulated.
const ids={},events={};
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.style={display:'none',setProperty(k,v){this[k]=v}};this.dataset={};this.children=[];this.attributes={};this.listeners={};this._text='';this.hidden=false;this.width=768;this.height=768;this.className='';this.classList={add:(...n)=>{this.className=[...new Set([...this.className.split(/\s+/),...n])].join(' ')},remove:(...n)=>{this.className=this.className.split(/\s+/).filter(x=>!n.includes(x)).join(' ')},contains:n=>this.className.split(/\s+/).includes(n),toggle:(n,v)=>{const yes=v===undefined?!this.classList.contains(n):v;this.classList[yes?'add':'remove'](n);return yes}};}
 set id(v){this._id=v;ids[v]=this;}get id(){return this._id||'';}
 set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
 set innerHTML(v){this.children=[];this._text='';const stack=[this];for(const token of String(v).match(/<[^>]+>|[^<]+/g)||[]){if(token.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(token.startsWith('<')){const m=token.match(/^<([\w-]+)/);if(!m)continue;const e=new Element(m[1]);for(const a of token.matchAll(/([\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g))e.setAttribute(a[1],a[2]??a[3]);stack.at(-1).appendChild(e);if(!/^(img|br|input|meta|link|hr)$/i.test(m[1])&&!token.endsWith('/>'))stack.push(e);}else stack.at(-1)._text+=token;}}
 get innerHTML(){return this._html||this.textContent;}
 setAttribute(k,v){v=String(v);this.attributes[k]=v;if(k==='id')this.id=v;if(k==='class')this.className=v;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=v;}
 getAttribute(k){return this.attributes[k]??null;}removeAttribute(k){delete this.attributes[k];}
 appendChild(e){e.remove();this.children.push(e);e.parentNode=this;return e;}append(...es){es.forEach(e=>this.appendChild(e));}prepend(e){e.remove();this.children.unshift(e);e.parentNode=this;}insertBefore(e,b){e.remove();let i=this.children.indexOf(b);if(i<0)i=this.children.length;this.children.splice(i,0,e);e.parentNode=this;return e;}remove(){if(this.parentNode){this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null;}}get parentElement(){return this.parentNode;}get firstChild(){return this.children[0];}
 contains(e){return e===this||this.children.some(c=>c.contains(e));}
 matches(s){s=s.trim();if(s.includes(' '))s=s.split(/\s+/).at(-1);if(s.startsWith('#'))return this.id===s.slice(1);if(s.startsWith('.'))return this.classList.contains(s.slice(1));const a=s.match(/^\[([^=\]]+)(?:=['"]?([^'"\]]+)['"]?)?\]$/);if(a)return a[2]===undefined?this.getAttribute(a[1])!==null:this.getAttribute(a[1])===a[2];return this.tagName.toLowerCase()===s.toLowerCase();}
 querySelectorAll(s){let a=[];for(const c of this.children){if(s.split(',').some(x=>c.matches(x)))a.push(c);a.push(...c.querySelectorAll(s));}return a;}querySelector(s){return this.querySelectorAll(s)[0]||null;}closest(s){return this.matches(s)?this:this.parentNode?.closest(s)||null;}
 addEventListener(n,f){(this.listeners[n]||=[]).push(f);}removeEventListener(){}click(){this.onclick?.({stopPropagation(){},preventDefault(){},target:this});for(const f of this.listeners.click||[])f({target:this});}focus(){}setPointerCapture(){}insertAdjacentHTML(_,v){const n=new Element();n.innerHTML=v;for(const c of [...n.children])this.appendChild(c);}
 getBoundingClientRect(){return {width:800,height:600,left:0,top:0,bottom:600,right:800};}
 getContext(){return new Proxy({canvas:this,measureText:t=>({width:String(t).length*9}),createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4)}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(t,k)=>k in t?t[k]:()=>{}});}
 toDataURL(){return '';}play(){return Promise.resolve();}pause(){}load(){}canPlayType(){return '';}set src(v){this._src=v;queueMicrotask(()=>{for(const f of this.listeners.load||[])f();});}get src(){return this._src;}
}
const element=tag=>new Element(tag),body=element('body'),head=element('head'),document={hidden:false,body,head,documentElement:element('html'),createElement:element,createElementNS:(_,tag)=>element(tag),getElementById:id=>ids[id]||null,querySelector:s=>body.querySelector(s)||head.querySelector(s),querySelectorAll:s=>[...body.querySelectorAll(s),...head.querySelectorAll(s)],addEventListener(n,f){(events[n]||=[]).push(f)}};
module.exports={element,document,events};
