// Real Chromium/WebGL UI regression; run with WW_PLAYWRIGHT and WW_CHROMIUM paths.
const {chromium}=require(process.env.WW_PLAYWRIGHT || 'playwright');
(async()=>{const fs=require('fs'),path=require('path');const server=require('http').createServer((req,res)=>{const p=path.join(path.resolve(__dirname,'..'),decodeURIComponent(req.url.split('?')[0])==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8877,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.WW_CHROMIUM || '/tmp/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:412,height:820},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8877',{waitUntil:'domcontentloaded'});await page.waitForTimeout(5000);await page.evaluate(async()=>{await loadApprovedPip();$('title').style.display='none';$('openingVideo51').style.display='none';voiceOn=false;home.tutorial219={done:{foot:true,car:true,sewer:true},step:{},started:{},carRevision:231};startHouse();});
await page.waitForTimeout(1600);await page.screenshot({path:'/tmp/home239.png'});
const before=await page.evaluate(()=>({placed:home.placed.length,boards:hs.house.userData.boards230.length,window:!!wallHome239,gardenGone:!root.userData.homeGarden231}));
if(before.boards!==60||!before.window||!before.gardenGone)throw Error('House integration incomplete');
await page.evaluate(()=>{home.tools.hammer230=true;inv.plank230=3;inv.nail=3;homestead230.state().mode='repair';const b=hs.house.userData.boards230.find(b=>!homestead230.state().boards[b.id]);rat.position.set(b.x,0,b.z);window.testRepair239=b.id;homestead230.begin();});
await page.waitForTimeout(2500);if(!await page.evaluate(()=>!!homestead230.state().boards[testRepair239]))throw Error('Actual repair action failed');
await page.evaluate(()=>{startScavenge();startHouse();});await page.waitForTimeout(1400);
if(!await page.evaluate(()=>!!homestead230.state().boards[testRepair239]))throw Error('Repair lost on house return');
await page.evaluate(()=>{openCraftBook();});const stray=await page.locator('button:visible').evaluateAll(bs=>bs.filter(b=>!b.closest('#modal')).map(b=>b.id));if(stray.length)throw Error('Menu overlap');
await page.evaluate(()=>{closeModal();});if(errors.length)throw Error(errors.join(';'));console.log(JSON.stringify({before,repairAndReturn:true,menuIsolation:true,errors}));await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});