const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path'),THREE=require('../three-r128-build55.js');
const node=()=>({textContent:'',style:{},addEventListener(){},appendChild(){},querySelector(){return node();}});let resolveDownload,started=0,stopped=0,clock=5000;
const ac={destination:{},createBufferSource(){return{connect(){return this;},disconnect(){},start(){started++;},stop(){stopped++;this.onended?.();}}},createGain(){return{gain:{value:0},connect(){return this;},disconnect(){}}},decodeAudioData(){return Promise.resolve({duration:2});}};
const ctx={THREE,console,Map,Set,Promise,performance:{now:()=>clock},fetch:()=>new Promise(r=>resolveDownload=()=>r({ok:true,arrayBuffer:()=>Promise.resolve(new ArrayBuffer(4))})),audio:()=>ac,voiceOn:true,document:{hidden:false,createElement:node,addEventListener(){}},gameplayActive:()=>true,rat:{position:new THREE.Vector3()},root:{},camera:new THREE.PerspectiveCamera(),sound66:{},speech69:{token:0},playVoice69(){},stopVoice69(){ctx.speech69.token++;if(ctx.speech69.current){ctx.speech69.current.source.stop();ctx.speech69.current=null;}},sfx:{},effect58(){throw Error('No synthetic bird/cat fallback');},tickWorld38(){},clear(){},$:node,recordings69:[],birdLines66:[],cockpit206:{groups:{Cabin:[]}},cockpit205:{drawer:node(),toggle(){}},modal(){},closeModal(){}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../audio207.js'),'utf8'),ctx);
const flush=()=>new Promise(r=>setImmediate(r));
(async()=>{
 assert(ctx.birdLines66.length===9);for(const cue of ctx.audio207.cues)assert(fs.existsSync(path.join(__dirname,'..',cue.file207)));
 ctx.tickWorld38(.016);ctx.meow66(new THREE.Vector3());ctx.voiceOn=false;ctx.tickWorld38(.016);resolveDownload();await flush();await flush();assert(started===0,'Download finishing after mute must stay silent');
 ctx.voiceOn=true;clock+=2000;ctx.meow66(new THREE.Vector3());await flush();assert(started===1,'Real cat recording plays');ctx.voiceOn=false;ctx.tickWorld38(.016);assert(stopped===1,'Mute stops in-flight animal playback');
 ctx.voiceOn=true;clock+=2000;ctx.effect58('bird',new THREE.Vector3());ctx.root={};ctx.tickWorld38(.016);resolveDownload();await flush();assert(started===1,'Scene changes discard pending bird sounds');
 const cue=ctx.audio207.cues[0];ctx.playVoice69(cue,new THREE.Vector3());ctx.stopVoice69();resolveDownload();await flush();assert(started===1,'Cancelled dialogue cannot start later');ctx.playVoice69(cue,new THREE.Vector3());await flush();assert(started===2);assert(ctx.sound66.voiceClock===2.3,'Dialogue follows decoded clip duration');
 console.log('PASS: nine bundled dialogue clips; mute, scene-change and asynchronous cancellation prevent stale audio');
})().catch(e=>{console.error(e);process.exitCode=1});
