const fs=require('fs'),vm=require('vm'),assert=require('assert'),THREE=require('../three-r128-build55.js');global.THREE=THREE;global.self=global;global.ProgressEvent=class{};require('../GLTFLoader.js');THREE.TextureLoader.prototype.load=function(url,cb){const t=new THREE.Texture();queueMicrotask(()=>cb(t));return t};const create=require('../roadster202.js'),data=fs.readFileSync(require('path').join(__dirname,'../rat-animation-pack67.glb'));new THREE.GLTFLoader().parse(data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),'',asset=>{
 const model=asset.scene,mixer=new THREE.AnimationMixer(model);mixer.clipAction(asset.animations.find(c=>c.name==='Idle_4')).play();mixer.update(0);model.updateMatrixWorld(true);const box=new THREE.Box3(),v=new THREE.Vector3();model.traverse(o=>{if(!o.isMesh)return;if(o.isSkinnedMesh)o.skeleton.update();for(let i=0;i<o.geometry.attributes.position.count;i++){v.fromBufferAttribute(o.geometry.attributes.position,i);if(o.isSkinnedMesh)o.boneTransform(i,v);o.localToWorld(v);box.expandByPoint(v);}});model.scale.setScalar(.5/(box.max.y-box.min.y));model.updateMatrixWorld(true);const dir=model.getObjectByName('headfront').getWorldPosition(new THREE.Vector3()).sub(model.getObjectByName('Head').getWorldPosition(new THREE.Vector3()));model.rotation.y=-Math.atan2(dir.x,dir.z);
 const rat=new THREE.Group();rat.add(model);const bones={},rest={};model.traverse(o=>{if(o.isBone){bones[o.name]=o;rest[o.name]=o.quaternion.clone();}});rat.userData={pipBones:bones,pipRest:rest,drive77:true};
 const el=()=>({style:{},classList:{add(){},remove(){}},setAttribute(){},appendChild(){},children:[{},{}]});const ctx={THREE,console,createRoadster202:create,rat,car77:null,document:{createElement:el,head:el(),body:el(),hidden:false,addEventListener(){}},carPanel77:el(),grab(){},enterCar77(){},exitCar77(){},disposeCar77(){},honk77(){},makeRat(){},tickGameplayCamera(){},gameCam:{ready:false,yaw:0,pitch:0},camera:new THREE.PerspectiveCamera(50,1,.1,100),addEventListener(){},gameplayActive:()=>true,sayToast(){},registerSolid62(){},phase:'scavenge',root:new THREE.Group(),keys:{},joy:{x:0,z:0},photo:{active:false},$:el,wallSolids:()=>[],resolveGeometry62(){},voiceOn:false,stopEngine77(){},tickWorld38(){},clear(){},control(){},weather42:()=>({rain:1}),markerText:()=>new THREE.Group(),radio:{},radioStop(){},radioStation(){},openYard201(){}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../driving203.js'),'utf8'),ctx);ctx.addCar77();ctx.car77.riding=true;ctx.car77.g.position.set(0,0,0);ctx.car77.g.rotation.y=0;
 const results=[];for(const steer of [-1,0,1])for(const kind of [null,'brake','gear','horn','radio']){ctx.car77.wheel.rotation.z=steer*.55;ctx.car77.reach=kind?{kind,time:.4,duration:.8}:null;rat.position.copy(ctx.car77.seat);ctx.roadsterControls203.pose(rat);results.push({steer,kind,errors:ctx.car77.handErrors203});}console.log('Maximum hand-contact error:',Math.max(...results.flatMap(r=>Object.values(r.errors))));assert(results.every(r=>Object.values(r.errors).every(e=>e<.008)),'Hands must reach controls within 8mm');
 ctx.car77.g.position.z=10;ctx.keys.w=true;for(let i=0;i<120;i++)ctx.controlCar77(1/60,{});assert(ctx.car77.speed>3);ctx.roadsterControls203.handbrake();for(let i=0;i<60;i++)ctx.controlCar77(1/60,{});assert(ctx.car77.speed===0);const headScale=bones.Head.scale.clone();ctx.roadsterControls203.view();ctx.roadsterControls203.pose(rat);ctx.tickGameplayCamera(.016);ctx.camera.aspect=.46;ctx.tickGameplayCamera(.016);ctx.camera.updateProjectionMatrix();ctx.camera.updateMatrixWorld(true);const visibleHands=['LeftHand','RightHand'].map(n=>bones[n].getWorldPosition(new THREE.Vector3()).project(ctx.camera));console.log('Cockpit hand screen coordinates:',visibleHands.map(v=>v.toArray()));assert(visibleHands.every(p=>Math.abs(p.x)<1&&Math.abs(p.y)<1&&p.z>-1&&p.z<1));assert(ctx.camera.near===.012);assert(bones.Head.scale.x<.001);ctx.roadsterControls203.view();let armCount=0;rat.traverse(m=>{if(m.isSkinnedMesh){armCount+=m.geometry.index.count;}});assert(armCount>0,'Hands-only keeps visible arm triangles');for(let i=0;i<3;i++)ctx.roadsterControls203.view();assert(bones.Head.scale.distanceTo(headScale)<1e-8);assert(ctx.camera.near===.1);console.log('PASS: controls reachable, brake stops driving, cockpit camera and head restore');
 vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../city204.js'),'utf8'),ctx);ctx.city204.seed();assert(ctx.city204.state.cars.length===6);assert(!ctx.blockedCar77(new THREE.Vector3(4,0,38),.12),'North gate is driveable');assert(!ctx.blockedCar77(new THREE.Vector3(4,0,42),.12));assert(ctx.blockedCar77(new THREE.Vector3(6,0,53),.12),'Buildings block cars');assert(ctx.blockedCar77(new THREE.Vector3(30,0,55),.12),'City edge stays bounded');
 const c=ctx.car77;c.g.position.set(4,0,39);c.handbrake=false;c.speed=4;c.drifting=true;ctx.keys.a=true;for(let i=0;i<10;i++)ctx.controlCar77(1/60,{});assert(Math.abs(c.travelYaw-c.g.rotation.y)>.03,'Drift separates momentum from heading');ctx.city204.release();ctx.keys.a=false;for(let i=0;i<30;i++)ctx.controlCar77(1/60,{});assert(!c.drifting);ctx.keys.w=false;
 ctx.city204.signal(-1);ctx.tickWorld38(.05);assert(c.indicator===-1);assert(c.indicators.some(l=>l.material.emissiveIntensity>0));ctx.city204.signal(-1);assert(c.indicator===0);const w=c.wipers[0].rotation.z;ctx.tickWorld38(.05);assert(c.wipers[0].rotation.z!==w,'Rain sweeps wipers');ctx.weather42=()=>({rain:0});for(let i=0;i<100;i++)ctx.tickWorld38(.05);assert(Math.abs(c.wipers[0].rotation.z-1.12)<.001,'Dry weather parks wipers');
 ctx.city204.tune();assert(c.reach.kind==='radio');assert(ctx.radio.preset204===0);ctx.city204.tune();assert(ctx.radio.preset204===1);
 const t=ctx.city204.state.cars[0];t.speed=2;const tangent=t.curve.getTangentAt(t.u).multiplyScalar(t.direction);c.g.position.copy(t.g.position).addScaledVector(tangent,2);for(let i=0;i<90;i++)ctx.tickWorld38(1/60);assert(t.speed<.05,'Traffic yields to player');assert(t.g.position.distanceTo(c.g.position)>=1.04,'Traffic does not run through player');console.log('PASS: city entry, boundaries, drift, rain wipers, indicators, radio and traffic yield');
 vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../smoking205.js'),'utf8'),ctx);c.speed=0;c.reach=null;c.drifting=false;ctx.pipSmoke205.toggle();assert(ctx.pipSmoke205.state);let maxSmokeError=0;for(let i=0;i<720;i++){ctx.roadsterControls203.pose(rat);ctx.pipSmoke205.tick(1/60);maxSmokeError=Math.max(maxSmokeError,...Object.values(ctx.pipSmoke205.state.errors));}console.log('Maximum smoking hand error:',maxSmokeError);assert(maxSmokeError<.015,'Cigarette and lighter remain within arm reach');assert(ctx.pipSmoke205.state.lit);assert(ctx.pipSmoke205.state.smoke.some(p=>p.age<1.7));ctx.roadsterControls203.view();ctx.roadsterControls203.pose(rat);assert(ctx.pipSmoke205.state.cig.position.toArray().every(Number.isFinite));ctx.pipSmoke205.toggle();for(let i=0;i<100;i++){ctx.roadsterControls203.pose(rat);ctx.pipSmoke205.tick(1/60);if(ctx.pipSmoke205.state)assert(Object.values(ctx.pipSmoke205.state.errors).every(e=>e<.018),'Put-out reaches ashtray');}assert(!ctx.pipSmoke205.state,'Putting out removes props and smoke');for(let i=0;i<4;i++)ctx.roadsterControls203.view();c.riding=false;rat.userData.drive77=false;ctx.pipSmoke205.toggle();assert(ctx.pipSmoke205.state,'Available on foot');ctx.pipSmoke205.pose(rat);rat.userData.air=true;ctx.pipSmoke205.tick(.016);assert(!ctx.pipSmoke205.state,'Jump interrupts cleanly');rat.userData.air=false;console.log('PASS: lighting, puffs, first person, put-out and movement interruption');
 Object.assign(ctx,{home:{pantry:{}},inv:{foil:12,nail:8},ITEMS:{foil:{name:'Foil'},nail:{name:'Nail'}},save(){},bag(){},bagCapacity:()=>30,totalBag(){return Object.values(ctx.inv).reduce((a,b)=>a+b,0)},craftEscape40:s=>s,modal(){},closeModal(){},engine77(){},cockpit205:{toggle(){}},renderer:{target:null,calls:0,render(){this.calls++},setRenderTarget(t){this.target=t},getRenderTarget(){return this.target}},scene:new THREE.Scene()});
 vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../motoring206.js'),'utf8'),ctx);const m=ctx.motoring206;m.attachCar();m.seed();assert(c.mirrors206.length===3);assert(m.world.benches.length===3);assert(m.transfer('foil',true,10)===10);assert(m.transfer('nail',true,8)===8);assert(m.transfer('foil',true,5)===2);assert(m.transfer('foil',true,1)===0);assert(m.transfer('foil',false,5)===5);assert(ctx.inv.foil===5);assert(m.transfer('foil',true,-4)===0);const saved=JSON.parse(JSON.stringify(ctx.home));ctx.home=saved;assert(m.data().stash.foil===7,'Glovebox survives save reload');
 c.riding=true;rat.userData.drive77=true;c.g.position.set(4,0,39);c.speed=0;ctx.keys.w=true;ctx.controlCar77(.033,{});assert(c.speed===0,'Ignition off blocks throttle');m.ignition();assert(c.ignition206);ctx.controlCar77(.033,{});assert(c.speed>0);c.speed=1;m.ignition();assert(c.ignition206,'Cannot cut moving engine');c.speed=0;ctx.keys.w=false;m.lights();ctx.tickWorld38(.05);assert(c.headlights206.every(l=>l.intensity>0));
 m.accept();assert(m.data().job.stage==='pickup');assert(!m.deliver(),'Remote delivery rejected');let dest=m.target();c.g.position.set(dest.x,0,dest.z);assert(m.deliver());assert(m.data().job.stage==='deliver');dest=m.target();c.g.position.set(dest.x,0,dest.z);assert(m.deliver());assert(!m.data().job);assert(m.data().deliveries===1&&ctx.home.pantry.foil===3);assert(!m.deliver(),'Cannot duplicate reward');
 c.g.position.set(-12,0,53);c.g.rotation.y=0;for(let i=0;i<50;i++)ctx.tickWorld38(.05);assert(m.data().parking.willow);assert(ctx.home.pantry.foil===5);for(let i=0;i<50;i++)ctx.tickWorld38(.05);assert(ctx.home.pantry.foil===5,'Parking rewards once');
 m.beginLook('left');assert(ctx.roadsterControls203.viewIndex===1);ctx.tickGameplayCamera(.016);m.endLook();assert(ctx.roadsterControls203.viewIndex===0);ctx.roadsterControls203.setView(2);ctx.roadsterControls203.pose(rat);ctx.tickWorld38(.12);ctx.renderer.render(ctx.scene,ctx.camera);assert(ctx.renderer.calls===2,'Mirror and main scene rendered');assert(ctx.renderer.target===null&&c.g.visible);assert(bones.Head.scale.x<.001,'Mirror restores first-person hidden head');ctx.roadsterControls203.setView(0);
 c.riding=false;rat.userData.drive77=false;rat.position.set(8,0,21);m.relax('sit');assert(m.rest);m.rest.time=1;m.restPose(rat);console.log('Sitting hand error',m.rest.errors);assert(Object.values(m.rest.errors).every(e=>e<.02));assert(Math.abs(bones.Hips.getWorldPosition(new THREE.Vector3()).y-.285)<.002);m.stand();assert(rat.position.distanceTo(new THREE.Vector3(8,0,21))<.001);c.g.position.set(5.4,0,17.6);rat.position.set(4.4,0,17.6);m.relax('lean');assert(m.rest);m.rest.time=1;m.restPose(rat);console.log('Leaning hand error',m.rest.errors);assert(Object.values(m.rest.errors).every(e=>e<.02));ctx.keys.w=true;ctx.control(.016,{});assert(!m.rest);console.log('PASS: ignition, lamps, mirrors, shoulder checks, storage, deliveries, parking, seated and leaning poses');




 // Build 207: outside view must frame the complete car on narrow phones.
 ctx.keys.w=false;c.riding=true;ctx.gameCam.pos=new THREE.Vector3();ctx.gameCam.distance=1.7;ctx.gameCam.pitch=.43;ctx.gameCam.yaw=Math.PI/2;
 const cameraHit=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8').match(/function cameraBoxHit\(origin[\s\S]*?return lo>\.05\?lo:null;}/)[0];vm.runInContext(cameraHit,ctx);
 vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../camera207.js'),'utf8'),ctx);
 for(const aspect of [.46,393/760,2]){ctx.camera.aspect=aspect;ctx.camera.updateProjectionMatrix();ctx.gameCam.ready=false;ctx.gameCam.distance=1.7;ctx.tickGameplayCamera(.016);ctx.camera.updateMatrixWorld(true);for(const x of [-.6,.6])for(const z of [-1,1])for(const y of [0,.85]){const point=c.g.position.clone().add(new THREE.Vector3(x,y,z)).project(ctx.camera);assert(Math.abs(point.x)<.85&&Math.abs(point.y)<.85,'Whole car has a margin in every viewport');}}
 ctx.camera.aspect=.46;ctx.camera.updateProjectionMatrix();ctx.gameCam.ready=false;ctx.gameCam.distance=1.7;ctx.wallSolids=()=>[{x:c.g.position.x+2,z:c.g.position.z,hx:.1,hz:1,h:2}];ctx.tickGameplayCamera(.016);assert(ctx.camera.position.distanceTo(c.g.position.clone().add(new THREE.Vector3(0,.34,0)))>=ctx.camera207.minimumDistance(.46,ctx.camera.fov)-.01,'Wall selects a clear angle instead of a face closeup');ctx.wallSolids=()=>[];
 ctx.roadsterControls203.setView(2);ctx.tickGameplayCamera(.016);assert(ctx.camera.near===.012,'Hands view still owns its camera');ctx.roadsterControls203.setView(0);
 console.log('PASS: portrait/landscape car framing, obstacle avoidance and first-person camera');

 // Expanded road network, higher speed and zero translation lag.
 const trafficPositions=ctx.city204.state.cars.map(t=>t.g.position.clone());ctx.city204.state.cars.forEach(t=>t.g.position.set(999,0,999));
 let roadSamples=0;for(const [a,b,z0,z1]of ctx.city204.roads209){const horizontal=b-a>z1-z0;for(let q=.03;q<.98;q+=.03){const p=new THREE.Vector3(horizontal?a+(b-a)*q:(a+b)/2,0,horizontal?(z0+z1)/2:z0+(z1-z0)*q);assert(!ctx.blockedCar77(p,.4),'Road centre must be driveable at '+p.toArray());roadSamples++;}}
 c.g.position.set(-70,0,65);c.g.rotation.y=Math.PI/2;c.travelYaw=c.g.rotation.y;c.speed=0;c.handbrake=false;c.ignition206=true;ctx.keys.w=true;for(let i=0;i<180;i++)ctx.controlCar77(1/60,{});assert(c.speed>8.9,'Car reaches increased top speed');ctx.keys.w=false;
 ctx.gameCam.ready=false;ctx.tickGameplayCamera(.016);const oldCamera=ctx.camera.position.clone();c.g.position.x+=.5;ctx.tickGameplayCamera(.016);assert(Math.abs(ctx.camera.position.x-oldCamera.x-.5)<1e-7,'Camera follows translation without trailing');
 ctx.city204.state.cars.forEach((t,i)=>t.g.position.copy(trafficPositions[i]));
 const canvasContext={fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fillText(){}};ctx.document.querySelector=()=>null;ctx.document.createElement=()=>({...el(),addEventListener(){},getContext:()=>canvasContext});ctx.$=()=>({...el(),addEventListener(){},click(){}});let mapReset=null;ctx.cockpit207={set(k,v){mapReset=[k,v];}};
 vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../touring209.js'),'utf8'),ctx);assert(mapReset[1]==='small','Map opens each session');
 assert(Math.abs(ctx.touring209.telemetry({speed:9,ignition206:true}).kph-32.4)<1e-8);assert(ctx.touring209.telemetry({speed:-2,ignition206:true}).gear==='R');assert(ctx.touring209.telemetry({speed:0,ignition206:false}).rpm===0);
 c.riding=false;const nearBefore=ctx.camera.near;ctx.touring209.toggleFoot(true);assert(ctx.touring209.firstPerson);ctx.tickGameplayCamera(.016);assert(Math.abs(ctx.camera.position.y-rat.position.y-.4)<1e-7);ctx.renderer.render(ctx.scene,ctx.camera);assert(rat.visible,'First-person render restores model visibility');ctx.touring209.toggleFoot(false);assert(ctx.camera.near===nearBefore);ctx.touring209.toggleFoot(true);ctx.enterCar77();assert(!ctx.touring209.firstPerson,'Entering car exits walking first person');
 assert(c.g.getObjectByName('Saddle leather door insert'));assert(c.g.getObjectByName('Walnut centre console'));
 console.log('PASS:',roadSamples,'road samples, increased speed, direct camera tracking, telemetry, walking first person and cabin trim');
},e=>{throw e});
