// CPU scene/logic integration check using the shipped Three.js and GLTFLoader.
// This is not a WebGL or browser visual test.
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert'),P=path.resolve(__dirname,'..');const THREE=require('../three-r128-build55.js');
const timers=[];function element(){const ev={};const e={style:{display:'none'},dataset:{},children:[],classList:{add(){},remove(){},toggle(){},contains(){return false;}},appendChild(o){this.children.push(o);return o;},append(){},remove(){},setAttribute(){},getAttribute(){return ''},addEventListener(n,f){ev[n]=f},removeEventListener(){},querySelector(){return element()},querySelectorAll(){return []},getBoundingClientRect(){return {width:800,height:600,left:0,top:0}},getContext(){return new Proxy({canvas:e,measureText:t=>({width:String(t).length*9}),createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),getImageData:(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4)}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})}, {get:(t,k)=>k in t?t[k]:()=>{}})},toDataURL(){return ''},play(){return Promise.resolve()},pause(){},load(){},canPlayType(){return ''},width:768,height:768};Object.defineProperty(e,'src',{set(v){queueMicrotask(()=>ev.load?.())}});return e;}
const elements={};const document={hidden:false,body:element(),head:element(),documentElement:element(),createElement:element,createElementNS:element,getElementById:id=>elements[id]||(elements[id]=element()),querySelector:()=>element(),querySelectorAll:()=>[],addEventListener(){}};
const fakeRenderer={shadowMap:{},capabilities:{isWebGL2:false,getMaxAnisotropy:()=>1},info:{render:{calls:0,triangles:0}},setPixelRatio(){},setSize(){},setClearColor(){},getPixelRatio:()=>1,render(){},dispose(){},domElement:element()};
const ctx={THREE,console,document,Blob,URL,TextDecoder,TextEncoder,ArrayBuffer,Uint8Array,Uint16Array,Uint32Array,Float32Array,performance,Math,Date,Map,Set,Promise,queueMicrotask,setTimeout:(f,ms)=>{if(ms<1000)return setTimeout(f,ms);timers.push(f);return 1},clearTimeout(){},setInterval(){},clearInterval(){},requestAnimationFrame(){},cancelAnimationFrame(){},addEventListener(){},removeEventListener(){},innerWidth:900,innerHeight:800,devicePixelRatio:1,matchMedia:()=>({matches:false,addEventListener(){}}),navigator:{userAgent:'scene-test',hardwareConcurrency:8},location:{search:'',href:'http://localhost',reload(){}},localStorage:{getItem:()=>null,setItem(){}},Image:function(){return element()},Audio:function(){return element()},fetch:async url=>{const file=path.join(P,String(url).split('?')[0]);return {ok:fs.existsSync(file),arrayBuffer:async()=>{const b=fs.readFileSync(file);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)},json:async()=>JSON.parse(fs.readFileSync(file,'utf8'))}},atob:s=>Buffer.from(s,'base64').toString('binary'),btoa:s=>Buffer.from(s,'binary').toString('base64'),__renderer:fakeRenderer};global.document=document;global.self=global;ctx.window=ctx;ctx.self=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(P,'GLTFLoader.js'),'utf8'),ctx);THREE.GLTFLoader.prototype.load=function(url,onLoad,onProgress,onError){try{const b=fs.readFileSync(path.join(P,url.split('?')[0]));this.parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'',onLoad,onError)}catch(e){onError?.(e)}};
let source=[...fs.readFileSync(path.join(P,'index.html'),'utf8').matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).join('\n');source=source.replace('const renderer=createRenderer55();','const renderer=__renderer;');
(async()=>{vm.runInContext(source,ctx,{filename:'game-inline.js'});await vm.runInContext('loadApprovedPip()',ctx);vm.runInContext('startScavenge()',ctx);await new Promise(r=>setTimeout(r,1800));console.log(vm.runInContext('({phase,assets:yard78.loaded,errors:yard78.errors,car:!!car77,rat:!!rat.userData.approvedPip,pool:yard78.pool?.name})',ctx));assert.equal(vm.runInContext('yard78.errors.length',ctx),0);assert.equal(vm.runInContext('yard78.loaded.length',ctx),6);assert.equal(vm.runInContext('yard78.pool?.name',ctx),'Clean striped inflatable kids pool');vm.runInContext('for(let i=0;i<30;i++){tickScavenge(1/60);tickWorld38(1/60);tickProps57(1/60);tick66(1/60)}',ctx);console.log('Scene and 30 gameplay ticks passed');
vm.runInContext(`
this.tests78={};root.updateMatrixWorld(true);tests78.legacyWood=root.children.filter(o=>/Batched backyard structures|Legacy wooden platform|Backyard picnic table/.test(o.name||'')).length;rat.userData.air=false;rat.userData.job67=null;
tests78.poolFloor=groundSurface57(-12.5,30.7,2)?.h;
rat.position.copy(yard78.rail.start);hangRail78();joy.x=1;for(let i=0;i<30;i++)control(1/60,{});tests78.railTravel=rat.userData.rail78.t;joy.x=0;dropRail78();tests78.railDrop=rat.userData.air;
rat.userData.air=false;rat.userData.job67=null;rat.position.copy(car77.g.position).add(new THREE.Vector3(1.7,0,0));tests78.carEntered=enterCar77();tests78.carBox=new THREE.Box3().setFromObject(car77.g).getSize(new THREE.Vector3()).toArray();keys.w=true;const begin=car77.g.position.clone();for(let i=0;i<60;i++){control(1/60,{});rat.animate(1/60,0);}keys.w=false;tests78.carTravel=begin.distanceTo(car77.g.position);tests78.driverScale=rat.scale.x;tests78.driverHeight=rat.position.y;car77.g.updateWorldMatrix(true,true);rat.updateWorldMatrix(true,true);tests78.handGaps=['Left','Right'].map((side)=>{const hand=rat.userData.pipBones[side+'Hand'];const target=car77.wheel.localToWorld(new THREE.Vector3(side==='Left'?-.095:.095,0,0));return hand?hand.getWorldPosition(new THREE.Vector3()).distanceTo(target):0;});car77.speed=0;exitCar77();tests78.carExited=!car77.riding;
rat.userData.job67=null;const f=yard78.finds[0],old=inv[f.item]||0;collectFind78(f);rat.userData.job67?.done?.();rat.userData.job67=null;collectFind78(f);tests78.oneTime=(inv[f.item]||0)-old===f.count&&!f.m.visible;
const sp=yard78.spider;rat.position.copy(sp.g.position).add(new THREE.Vector3(.7,0,0));sp.aware=true;tailHit67(rat);tests78.spiderRetreat=sp.scared>0;spiderTick78(.1);
gate57.open=true;for(let i=0;i<60;i++)tickProps57(1/60);tests78.gateAngle=gate57.leaf.rotation.y;
rat.userData.air=false;rat.userData.job67=null;rat.position.set(9,0,23);startPole82({x:9,t:0});joy.z=-1;for(let i=0;i<150;i++)control(1/60,{});joy.z=0;tests78.wireReached=!!rat.userData.wire82;joy.x=1;for(let i=0;i<45;i++){control(1/60,{});tickWorld38(1/60);}joy.x=0;tests78.wireTravel=rat.userData.wire82?.t||0;tests78.wireFinite=rat.position.toArray().every(Number.isFinite);dropWire82();tests78.wireDrop=rat.userData.air;
this.hasFinite78=true;root.updateMatrixWorld(true);root.traverse(o=>{if(!o.matrixWorld.elements.every(Number.isFinite))hasFinite78=false;});
`,ctx);
const checks=ctx.tests78;console.log('Interaction checks',checks);assert.equal(checks.legacyWood,0);assert(checks.railTravel>0);assert(checks.railDrop);assert(checks.carEntered);assert(checks.carBox[0]<2&&checks.carBox[2]<2);assert(checks.driverScale<1);assert(checks.driverHeight>0&&checks.driverHeight<1.2);assert(checks.handGaps.every(n=>n<.2));assert(checks.carTravel>.1);assert(checks.carExited);assert(checks.oneTime);assert(checks.spiderRetreat);assert(checks.gateAngle>1.4);assert(checks.wireReached);assert(checks.wireTravel>.02);assert(checks.wireFinite);assert(checks.wireDrop);assert(ctx.hasFinite78);
fs.writeFileSync(path.join(P,'verification78.json'),JSON.stringify(vm.runInContext('({interactionChecks:tests78,assets:yard78.loaded,errors:yard78.errors,finds:yard78.finds.map(f=>f.id),spiderAnimations:Object.keys(yard78.spider.actions),ratAnimations:Object.keys(rat.userData.pipActions).filter(n=>n.startsWith("Drive_")),meshCount:surfaces57.length})',ctx),null,2));})().catch(e=>{console.error(e.message,String(e.stack).split("\n").slice(-8).join("\n"));process.exitCode=1});
